// src/views/SettingsView.vue
﻿<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { useI18n } from 'vue-i18n'
import { useBabyStore } from '@/stores/baby'
import { countAllRecords, clearAllData } from '@/db'
import { exportBabyCsvs, exportAllBabiesCsv, importAllCsv } from '@/services/export'
import { BABY_AVATARS } from '@/constants'
import { loadReminders, saveReminders, type ReminderConfig, type ReminderType } from '@/utils/reminderScheduler'
import PageHeader from '@/components/common/PageHeader.vue'
import BaseModal from '@/components/common/BaseModal.vue'
import ReminderParam from '@/components/settings/ReminderParam.vue'
import type { Baby, BabyGender } from '@/types'

const babyStore = useBabyStore()
const { t } = useI18n()

const recordCounts = ref({
  feedings: 0,
  diapers: 0,
  pumpings: 0,
  sleeps: 0,
  growths: 0,
  solidFoods: 0,
  medications: 0,
  vaccinations: 0,
  temperatures: 0,
  milestones: 0,
})
const babyModal = ref<{ mode: 'add' | 'edit'; id?: number } | null>(null)
const babyName = ref('')
const babyGender = ref<BabyGender | ''>('')
const babyBirthDate = ref('')
const babyAvatar = ref('')
const deleteBabyConfirm = ref<Baby | null>(null)
const exportSuccess = ref(false)
const importBusy = ref(false)
const importFileRef = ref<HTMLInputElement | null>(null)
const clearAllConfirm = ref(false)
const clearBusy = ref(false)

// —— 分享给朋友 ——
const shareFeedback = ref<string | null>(null)

/** 当前部署地址（分享链接） */
const shareUrl = computed(() => {
  const { origin, pathname } = window.location
  return `${origin}${pathname}`
})

async function handleShare() {
  shareFeedback.value = null
  const url = shareUrl.value
  const text = `${t('settings.shareText')} ${url}`
  if (navigator.share) {
    try {
      await navigator.share({ title: t('settings.shareTitle'), text, url })
      return
    } catch (e) {
      // 用户主动取消分享（AbortError）时静默退出，不降级复制
      if ((e as Error)?.name === 'AbortError') return
    }
  }
  // 降级：复制推荐语 + 链接到剪贴板
  try {
    await navigator.clipboard.writeText(text)
    shareFeedback.value = t('common.copied')
  } catch {
    try {
      const ta = document.createElement('textarea')
      ta.value = text
      ta.style.position = 'fixed'
      ta.style.opacity = '0'
      document.body.appendChild(ta)
      ta.select()
      document.execCommand('copy')
      document.body.removeChild(ta)
      shareFeedback.value = t('common.copied')
    } catch {
      shareFeedback.value = `${t('settings.shareFallback')} ${url}`
    }
  }
  window.setTimeout(() => (shareFeedback.value = null), 3000)
}

const activeBaby = computed(() => babyStore.babies.find((b) => b.id === babyStore.activeBabyId))

// —— 提醒设置（多类提醒，默认全部关闭，由用户自行开启）——
const reminders = ref<ReminderConfig>(loadReminders())

async function requestNotificationPermission(): Promise<boolean> {
  if (!('Notification' in window)) return false
  if (Notification.permission === 'granted') return true
  if (Notification.permission === 'default') {
    try {
      const p = await Notification.requestPermission()
      return p === 'granted'
    } catch {
      return false
    }
  }
  return false
}

async function toggleReminder(type: ReminderType) {
  reminders.value[type].enabled = !reminders.value[type].enabled
  if (reminders.value[type].enabled) await requestNotificationPermission()
  saveReminders(reminders.value)
}

function persistReminders() {
  saveReminders(reminders.value)
}

/** 间隔类提醒参数更新（组件统一回调，转 number 后写回配置） */
function setIntervalReminder(type: 'feed' | 'medication' | 'diaper' | 'sleep', v: number | string) {
  reminders.value[type].intervalHours = typeof v === 'number' ? v : Number(v)
}

/** 时间类提醒参数更新 */
function setSleepTime(v: number | string) {
  reminders.value.sleep.time = String(v)
}

const reminderRows = computed(() => [
  { type: 'feed' as const, title: t('reminders.feed.title'), sub: t('reminders.feed.sub') },
  { type: 'sleep' as const, title: t('reminders.sleep.title'), sub: t('reminders.sleep.sub') },
  { type: 'medication' as const, title: t('reminders.medication.title'), sub: t('reminders.medication.sub') },
  { type: 'vaccination' as const, title: t('reminders.vaccination.title'), sub: t('reminders.vaccination.sub') },
  { type: 'diaper' as const, title: t('reminders.diaper.title'), sub: t('reminders.diaper.sub') },
])

onMounted(async () => {
  recordCounts.value = await countAllRecords()
})

function openAddBaby() {
  babyName.value = ''
  babyGender.value = ''
  babyBirthDate.value = ''
  babyAvatar.value = ''
  babyModal.value = { mode: 'add' }
}

function openEditBaby(b: Baby) {
  babyName.value = b.name
  babyGender.value = b.gender ?? ''
  babyBirthDate.value = b.birthDate ?? ''
  babyAvatar.value = b.avatar ?? ''
  babyModal.value = { mode: 'edit', id: b.id }
}

async function saveBaby() {
  const name = babyName.value.trim()
  // 宝宝名称/性别/出生日期均为必填（出生日期用于月龄换算与生长曲线参考线）
  if (!name || !babyBirthDate.value) return
  if (babyModal.value?.mode === 'add' && !babyGender.value) return
  if (babyModal.value?.mode === 'edit' && babyModal.value.id != null) {
    await babyStore.updateBaby(babyModal.value.id, {
      name,
      gender: babyGender.value || undefined,
      birthDate: babyBirthDate.value,
      avatar: babyAvatar.value || undefined,
    })
  } else {
    await babyStore.addBaby(
      name,
      babyGender.value || undefined,
      babyBirthDate.value,
      undefined,
      undefined,
      babyAvatar.value || undefined,
    )
  }
  babyModal.value = null
}

async function confirmDeleteBaby() {
  const id = deleteBabyConfirm.value?.id
  if (id == null) return
  await babyStore.deleteBaby(id)
  deleteBabyConfirm.value = null
}

function babyAge(b: Baby): string {
  if (!b.birthDate) return t('settings.noBirthDate')
  const diff = Date.now() - new Date(b.birthDate + 'T00:00:00').getTime()
  if (diff < 0) return t('settings.birthdayUpcoming')
  const months = Math.floor(diff / (1000 * 60 * 60 * 24 * 30.44))
  if (months < 1) {
    const days = Math.floor(diff / (1000 * 60 * 60 * 24))
    return t('settings.ageDays', { n: days })
  }
  if (months < 12) return t('settings.ageMonths', { n: months })
  const years = Math.floor(months / 12)
  return t('settings.ageYears', { years, months: months % 12 })
}

async function handleExportBabyCsv() {
  if (!activeBaby.value) return
  await exportBabyCsvs(activeBaby.value)
  exportSuccess.value = true
  setTimeout(() => (exportSuccess.value = false), 3000)
}

async function handleExportAllCsv() {
  await exportAllBabiesCsv()
  exportSuccess.value = true
  setTimeout(() => (exportSuccess.value = false), 3000)
}

async function handleImportFile(e: Event) {
  const input = e.target as HTMLInputElement
  const file = input.files?.[0]
  if (!file) return
  importBusy.value = true
  try {
    const result = await importAllCsv(file)
    alert(
      t('settings.importSuccess', {
        babies: result.babies,
        feedings: result.feedings,
        diapers: result.diapers,
        pumpings: result.pumpings,
        sleeps: result.sleeps,
        growths: result.growths,
        solidFoods: result.solidFoods,
        medications: result.medications,
        vaccinations: result.vaccinations,
        temperatures: result.temperatures,
        milestones: result.milestones,
      }),
    )
    recordCounts.value = await countAllRecords()
  } catch {
    alert(t('settings.importFailed'))
  } finally {
    importBusy.value = false
    if (importFileRef.value) importFileRef.value.value = ''
  }
}

async function confirmClearAll() {
  clearBusy.value = true
  try {
    await clearAllData()
    // 同步重置内存中的当前宝宝，避免残留旧 id 在后续导入时"巧合命中"
    babyStore.activeBabyId = null
    localStorage.removeItem('babysitter.activeBabyId')
    recordCounts.value = {
      feedings: 0,
      diapers: 0,
      pumpings: 0,
      sleeps: 0,
      growths: 0,
      solidFoods: 0,
      medications: 0,
      vaccinations: 0,
      temperatures: 0,
      milestones: 0,
    }
    clearAllConfirm.value = false
  } finally {
    clearBusy.value = false
  }
}
</script>

<template>
  <div class="page settings-page">
    <PageHeader />

    <!-- 宝宝管理 -->
    <p class="section-title">{{ t('settings.babyManage') }}</p>
    <div class="card">
      <div class="baby-list">
        <div
          v-for="b in babyStore.babies"
          :key="b.id"
          class="baby-item"
          :class="{ active: b.id === babyStore.activeBabyId }"
          @click="b.id != null && babyStore.selectBaby(b.id)"
        >
          <div class="baby-avatar" :style="{ background: b.avatarColor }">{{ b.avatar ?? b.name[0] }}</div>
          <div class="baby-info">
            <p class="baby-name">{{ b.name }}{{ b.id === babyStore.activeBabyId ? t('common.current') : '' }}</p>
            <p class="baby-meta">
              {{ b.gender ? t(b.gender === 'boy' ? 'settings.genderBoy' : 'settings.genderGirl') : t('settings.genderUnknown') }}
              · {{ babyAge(b) }}
            </p>
          </div>
          <div class="baby-actions">
            <button class="icon-btn" :title="t('common.edit')" @click.stop="openEditBaby(b)">✏️</button>
            <button class="icon-btn" :title="t('common.delete')" @click.stop="deleteBabyConfirm = b">🗑️</button>
          </div>
        </div>
      </div>
      <button class="btn btn-outline btn-block" @click="openAddBaby">+ {{ t('settings.addBaby') }}</button>
    </div>

    <!-- 提醒设置 -->
    <p class="section-title">{{ t('settings.reminderSectionTitle') }}</p>
    <div class="card">
      <p class="data-tip">{{ t('settings.reminderTip') }}</p>
      <div v-for="r in reminderRows" :key="r.type" class="reminder-block">
        <div class="reminder-row">
          <div class="reminder-info">
            <p class="reminder-title">{{ r.title }}</p>
            <p class="reminder-sub">{{ r.sub }}</p>
          </div>
          <button
            class="switch"
            :class="{ on: reminders[r.type].enabled }"
            role="switch"
            :aria-checked="reminders[r.type].enabled"
            @click="toggleReminder(r.type)"
          >
            <span class="switch-knob"></span>
          </button>
        </div>
        <div v-if="reminders[r.type].enabled && r.type !== 'vaccination'" class="reminder-param">
          <ReminderParam
            v-if="r.type === 'feed'"
            mode="interval"
            :label="t('reminders.intervalLabel')"
            :model-value="reminders.feed.intervalHours"
            :min="0"
            :step="0.5"
            :placeholder="t('reminders.intervalPh', { n: '2.5' })"
            :hint="t('reminders.feed.hint')"
            @update:model-value="(v) => setIntervalReminder('feed', v)"
            @change="persistReminders"
          />
          <ReminderParam
            v-else-if="r.type === 'sleep'"
            mode="time"
            :label="t('reminders.sleepTimeLabel')"
            :model-value="reminders.sleep.time"
            :placeholder="t('common.selectTime')"
            @update:model-value="setSleepTime"
            @change="persistReminders"
          />
          <ReminderParam
            v-if="r.type === 'sleep' && reminders.sleep.enabled"
            mode="interval"
            :label="t('reminders.intervalLabel')"
            :model-value="reminders.sleep.intervalHours"
            :min="0"
            :step="1"
            :placeholder="t('reminders.intervalPh', { n: '4' })"
            :hint="t('reminders.sleep.hint')"
            @update:model-value="(v) => setIntervalReminder('sleep', v)"
            @change="persistReminders"
          />
          <ReminderParam
            v-else-if="r.type === 'medication'"
            mode="interval"
            :label="t('reminders.intervalLabel')"
            :model-value="reminders.medication.intervalHours"
            :min="1"
            :step="1"
            :placeholder="t('reminders.intervalPh', { n: '6' })"
            :hint="t('reminders.medication.hint')"
            @update:model-value="(v) => setIntervalReminder('medication', v)"
            @change="persistReminders"
          />
          <ReminderParam
            v-else-if="r.type === 'diaper'"
            mode="interval"
            :label="t('reminders.intervalLabel')"
            :model-value="reminders.diaper.intervalHours"
            :min="1"
            :step="1"
            :placeholder="t('reminders.intervalPh', { n: '6' })"
            :hint="t('reminders.diaper.hint')"
            @update:model-value="(v) => setIntervalReminder('diaper', v)"
            @change="persistReminders"
          />
        </div>
      </div>
    </div>

    <!-- 分享给朋友 -->
    <p class="section-title">{{ t('settings.shareSection') }}</p>
    <div class="card">
      <p class="data-tip">{{ t('settings.shareTip') }}</p>
      <button class="btn btn-primary btn-block" @click="handleShare">{{ t('settings.shareBtn') }}</button>
      <p v-if="shareFeedback" class="export-ok">{{ shareFeedback }}</p>
    </div>

    <!-- 数据管理 -->
    <p class="section-title">{{ t('settings.dataManage') }}</p>
    <div class="card">
      <p class="data-tip">{{ t('settings.dataTip') }}</p>
      <div class="data-counts">
        <span>{{ t('log.filters.feeding') }} {{ t('common.records', { n: recordCounts.feedings }) }}</span>
        <span>{{ t('log.filters.diaper') }} {{ t('common.records', { n: recordCounts.diapers }) }}</span>
        <span>{{ t('log.filters.pumping') }} {{ t('common.records', { n: recordCounts.pumpings }) }}</span>
        <span>{{ t('log.filters.sleep') }} {{ t('common.records', { n: recordCounts.sleeps }) }}</span>
        <span>{{ t('log.filters.growth') }} {{ t('common.records', { n: recordCounts.growths }) }}</span>
        <span>{{ t('log.filters.solidFood') }} {{ t('common.records', { n: recordCounts.solidFoods }) }}</span>
        <span>{{ t('log.filters.medication') }} {{ t('common.records', { n: recordCounts.medications }) }}</span>
        <span>{{ t('log.filters.vaccination') }} {{ t('common.records', { n: recordCounts.vaccinations }) }}</span>
        <span>{{ t('log.filters.temperature') }} {{ t('common.records', { n: recordCounts.temperatures }) }}</span>
        <span>{{ t('log.filters.milestone') }} {{ t('common.records', { n: recordCounts.milestones }) }}</span>
      </div>
      <button class="btn btn-primary btn-block" :disabled="activeBaby === undefined" @click="handleExportBabyCsv">
        <span class="btn-label">{{
          activeBaby ? t('settings.exportBabyCsv', { name: activeBaby.name }) : t('common.noBaby')
        }}</span>
      </button>
      <button class="btn btn-outline btn-block" @click="handleExportAllCsv">{{ t('settings.exportAllCsv') }}</button>
      <button class="btn btn-outline btn-block" :disabled="importBusy" @click="importFileRef?.click()">
        {{ importBusy ? t('common.importing') : t('common.importCsv') }}
      </button>
      <input ref="importFileRef" type="file" accept=".csv,text/csv" hidden @change="handleImportFile" />
      <p v-if="exportSuccess" class="export-ok">{{ t('settings.exportOk') }}</p>
      <button class="btn btn-danger-soft btn-block" @click="clearAllConfirm = true">
        {{ t('settings.clearAll') }}
      </button>
    </div>

    <!-- 关于 -->
    <p class="section-title">{{ t('settings.about') }}</p>
    <div class="card">
      <p class="about-text">{{ t('settings.aboutText1') }}</p>
      <p class="about-text">{{ t('settings.aboutText2') }}</p>
      <p class="about-text">{{ t('settings.aboutText3') }}</p>
      <p class="about-text muted">{{ t('settings.aboutMuted') }}</p>
    </div>

    <!-- 宝宝编辑弹窗 -->
    <BaseModal
      :show="babyModal !== null"
      :title="babyModal?.mode === 'edit' ? t('settings.editBaby') : t('settings.addBaby')"
      @close="babyModal = null"
    >
      <div class="form-field">
        <label class="form-label">{{ t('settings.babyName') }} *</label>
        <input v-model="babyName" type="text" :placeholder="t('settings.babyNamePh')" class="form-input" />
      </div>
      <div class="form-field">
        <label class="form-label">{{ t('settings.genderLabel') }} {{ babyModal?.mode === 'add' ? '*' : '' }}</label>
        <div class="gender-picker" role="radiogroup">
          <button
            type="button"
            class="gender-option"
            :class="{ selected: babyGender === 'boy' }"
            :aria-checked="babyGender === 'boy'"
            role="radio"
            @click="babyGender = 'boy'"
          >
            <span class="gender-emoji">👦</span>{{ t('settings.genderBoy') }}
          </button>
          <button
            type="button"
            class="gender-option"
            :class="{ selected: babyGender === 'girl' }"
            :aria-checked="babyGender === 'girl'"
            role="radio"
            @click="babyGender = 'girl'"
          >
            <span class="gender-emoji">👧</span>{{ t('settings.genderGirl') }}
          </button>
        </div>
      </div>
      <div class="form-field">
        <label class="form-label">{{ t('settings.birthDate') }} *</label>
        <input v-model="babyBirthDate" type="date" :placeholder="t('common.selectDate')" class="form-input" />
      </div>
      <div class="form-field">
        <label class="form-label">{{ t('settings.avatarLabel') }}</label>
        <div class="avatar-picker">
          <button
            v-for="a in BABY_AVATARS"
            :key="a"
            type="button"
            class="avatar-option"
            :class="{ selected: babyAvatar === a }"
            @click="babyAvatar = a"
          >
            {{ a }}
          </button>
        </div>
      </div>
      <div class="form-actions">
        <button class="btn btn-outline" @click="babyModal = null">{{ t('common.cancel') }}</button>
        <button
          class="btn btn-primary"
          :disabled="!babyName.trim() || !babyBirthDate || (babyModal?.mode === 'add' && !babyGender)"
          @click="saveBaby"
        >
          {{ t('settings.saveBaby') }}
        </button>
      </div>
    </BaseModal>

    <!-- 删除宝宝确认 -->
    <BaseModal
      :show="deleteBabyConfirm !== null"
      :title="t('settings.deleteBabyTitle')"
      @close="deleteBabyConfirm = null"
    >
      <p class="confirm-text">{{ t('settings.deleteBabyText', { name: deleteBabyConfirm?.name ?? '' }) }}</p>
      <div class="form-actions">
        <button class="btn btn-outline" @click="deleteBabyConfirm = null">{{ t('common.cancel') }}</button>
        <button class="btn btn-danger-soft" @click="confirmDeleteBaby">{{ t('log.confirmDelete') }}</button>
      </div>
    </BaseModal>

    <!-- 清空数据确认 -->
    <BaseModal :show="clearAllConfirm" :title="t('settings.clearConfirmTitle')" @close="clearAllConfirm = false">
      <p class="confirm-text">{{ t('settings.clearConfirmText') }}</p>
      <div class="form-actions">
        <button class="btn btn-outline" @click="clearAllConfirm = false">{{ t('common.cancel') }}</button>
        <button class="btn btn-danger-soft" :disabled="clearBusy" @click="confirmClearAll">
          {{ t('settings.confirmClear') }}
        </button>
      </div>
    </BaseModal>
  </div>
</template>

<style scoped>
.baby-list {
  display: flex;
  flex-direction: column;
  gap: 8px;
  margin-bottom: 10px;
}

.baby-item {
  display: flex;
  align-items: center;
  gap: 12px;
  padding: 10px 12px;
  border-radius: var(--radius-lg);
  border: 1px solid var(--glass-border);
  background: var(--surface);
  backdrop-filter: var(--glass-blur);
  -webkit-backdrop-filter: var(--glass-blur);
  cursor: pointer;
  box-shadow: var(--shadow-glass);
  transition: all 0.3s var(--spring);
}

.baby-item:active {
  transform: scale(0.985);
}

@media (max-width: 400px) {
  .baby-item {
    gap: 10px;
    padding: 10px;
  }

  .baby-avatar {
    width: 44px;
    height: 44px;
    font-size: 16px;
  }

  .baby-actions {
    gap: 4px;
  }
}

.baby-item.active {
  border-color: var(--primary);
  background: var(--primary-soft);
  box-shadow: var(--shadow-glass), 0 0 0 3px rgba(238, 122, 85, 0.12);
}

.baby-avatar {
  width: 44px;
  height: 44px;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  color: #fff;
  font-size: 18px;
  font-weight: 700;
  flex-shrink: 0;
}

.baby-info {
  flex: 1;
  min-width: 0;
}

.baby-name {
  font-size: 15px;
  font-weight: 700;
  color: var(--text);
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.baby-meta {
  font-size: 12px;
  color: var(--text-muted);
  margin-top: 2px;
}

.baby-actions {
  display: flex;
  gap: 6px;
  flex-shrink: 0;
}

.icon-btn {
  width: 44px;
  height: 44px;
  min-height: 0;
  border-radius: var(--radius);
  border: 1px solid var(--glass-border);
  background: rgba(255, 255, 255, 0.65);
  backdrop-filter: var(--glass-blur-light);
  -webkit-backdrop-filter: var(--glass-blur-light);
  font-size: 17px;
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;
  transition:
    background 0.25s var(--ease-out),
    transform 0.3s var(--spring);
}

:global([data-theme='dark']) .icon-btn {
  background: rgba(58, 58, 62, 0.7);
}

.icon-btn:active {
  transform: scale(0.92);
}

.data-tip {
  font-size: 12px;
  color: var(--text-muted);
  margin-bottom: 8px;
  line-height: 1.6;
}

.reminder-row {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 12px;
}

.reminder-info {
  flex: 1;
  min-width: 0;
}

.reminder-title {
  font-size: 14px;
  font-weight: 700;
  color: var(--text);
}

.reminder-sub {
  font-size: 12px;
  color: var(--text-muted);
  margin-top: 3px;
  line-height: 1.5;
}

.reminder-hint {
  font-size: 11px;
  color: var(--text-muted);
  margin-top: 10px;
  line-height: 1.7;
}

.reminder-block {
  padding: 4px 0 10px;
}

.reminder-block + .reminder-block {
  border-top: 1px dashed var(--border);
  padding-top: 10px;
}

.reminder-param {
  display: flex;
  align-items: center;
  flex-wrap: wrap;
  gap: 8px;
  margin-top: 8px;
  padding: 8px 10px;
  background: var(--surface-2);
  border: 1px solid var(--glass-border);
  border-radius: var(--radius-sm);
  backdrop-filter: var(--glass-blur-light);
  -webkit-backdrop-filter: var(--glass-blur-light);
}

.switch {
  position: relative;
  width: 48px;
  height: 28px;
  min-height: 0; /* 覆盖全局 button 的 min-height:44px，保持开关比例 */
  border-radius: 999px;
  border: none;
  background: var(--border);
  transition: background 0.3s var(--ease-out);
  flex-shrink: 0;
  cursor: pointer;
  padding: 0;
}

.switch.on {
  background: var(--primary);
}

.switch-knob {
  position: absolute;
  top: 3px;
  left: 3px;
  width: 22px;
  height: 22px;
  border-radius: 50%;
  background: #fff;
  transition: transform 0.35s var(--spring);
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.2);
}

.switch.on .switch-knob {
  transform: translateX(20px);
}

.data-counts {
  display: flex;
  flex-wrap: wrap;
  gap: 6px;
  margin-bottom: 14px;
}

.data-counts span {
  font-size: 11px;
  font-weight: 600;
  color: var(--text-secondary);
  background: rgba(255, 255, 255, 0.6);
  backdrop-filter: var(--glass-blur-light);
  -webkit-backdrop-filter: var(--glass-blur-light);
  border: 1px solid var(--glass-border);
  padding: 4px 11px;
  border-radius: 999px;
}

:global([data-theme='dark']) .data-counts span {
  background: rgba(44, 44, 48, 0.55);
}

.btn-block {
  margin-top: 10px;
}

.btn-block .btn-label {
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  max-width: 100%;
}

.export-ok {
  font-size: 12px;
  color: #7fae6c;
  text-align: center;
  margin-top: 8px;
}

.about-text {
  font-size: 13px;
  color: var(--text-secondary);
  line-height: 1.8;
}

.about-text.muted {
  color: var(--text-muted);
  font-size: 12px;
}

.confirm-text {
  font-size: 14px;
  color: var(--text);
  line-height: 1.7;
  margin-bottom: 18px;
}

.avatar-picker {
  display: grid;
  grid-template-columns: repeat(6, 1fr);
  gap: 6px;
}

.gender-picker {
  display: grid;
  grid-template-columns: repeat(2, 1fr);
  gap: 8px;
}

.gender-option {
  min-height: 44px;
  padding: 6px 8px;
  border-radius: var(--radius);
  border: 1px solid var(--glass-border);
  background: rgba(255, 255, 255, 0.65);
  backdrop-filter: var(--glass-blur-light);
  -webkit-backdrop-filter: var(--glass-blur-light);
  font-size: 14px;
  font-weight: 600;
  color: var(--text-secondary);
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 6px;
  transition: all 0.3s var(--spring);
}

:global([data-theme='dark']) .gender-option {
  background: rgba(58, 58, 62, 0.7);
}

.gender-option.selected {
  border-color: var(--primary);
  background: var(--primary-soft);
  color: var(--primary-dark);
  transform: scale(1.02);
}

.gender-emoji {
  font-size: 16px;
}

/* PC/平板：设置页为表单型页面，限宽居中避免内容被拉得过宽 */
@media (min-width: 900px) {
  .settings-page {
    max-width: 720px;
    margin: 0 auto;
  }

  .avatar-picker {
    max-width: 480px;
    margin: 0 auto;
  }
}

.avatar-option {
  min-height: 44px;
  padding: 4px;
  border-radius: var(--radius-sm);
  border: 1px solid var(--glass-border);
  background: rgba(255, 255, 255, 0.65);
  backdrop-filter: var(--glass-blur-light);
  -webkit-backdrop-filter: var(--glass-blur-light);
  font-size: 20px;
  display: flex;
  align-items: center;
  justify-content: center;
  transition: all 0.3s var(--spring);
}

:global([data-theme='dark']) .avatar-option {
  background: rgba(58, 58, 62, 0.7);
}

.avatar-option.selected {
  border-color: var(--primary);
  background: var(--primary-soft);
  transform: scale(1.06);
}

.form-actions {
  display: flex;
  gap: 10px;
}

.form-actions .btn {
  flex: 1;
}
</style>

// src/views/SettingsView.tsx
'use client'

import { useEffect, useMemo, useRef, useState } from 'react'
import { useTranslation } from 'react-i18next'
import PageHeader from '@/components/common/PageHeader'
import BaseModal from '@/components/common/BaseModal'
import ReminderParam from '@/components/settings/ReminderParam'
import { countAllRecords, clearAllData, clearBabyData, db } from '@/db'
import { exportBabyCsvs, exportAllBabiesCsv, importAllCsv } from '@/services/export'
import { BABY_AVATARS } from '@/constants'
import { loadReminders, saveReminders, type ReminderConfig, type ReminderType } from '@/utils/reminderScheduler'
import { useBabies } from '@/stores/baby'
import type { Baby, BabyGender } from '@/types'
import s from './SettingsView.module.css'

export default function SettingsView() {
  const { t } = useTranslation()
  const { babies, activeBaby, activeBabyId, setActiveBabyId, addBaby } = useBabies()

  useEffect(() => {
    document.title = `${t('nav.settings')} · ${t('app.name')}`
  }, [t])

  const [recordCounts, setRecordCounts] = useState({
    feedings: 0,
    diapers: 0,
    pumpings: 0,
    sleeps: 0,
    growths: 0,
    solidFoods: 0,
    medications: 0,
    vaccinations: 0,
    temperatures: 0,
    milestones: 0,
  })
  const [babyModal, setBabyModal] = useState<{ mode: 'add' | 'edit'; id?: number } | null>(null)
  const [babyName, setBabyName] = useState('')
  const [babyGender, setBabyGender] = useState<BabyGender | ''>('')
  const [babyBirthDate, setBabyBirthDate] = useState('')
  const [babyAvatar, setBabyAvatar] = useState('')
  const [deleteBabyConfirm, setDeleteBabyConfirm] = useState<Baby | null>(null)
  const [exportSuccess, setExportSuccess] = useState(false)
  const [importBusy, setImportBusy] = useState(false)
  const importFileRef = useRef<HTMLInputElement | null>(null)
  const [clearAllConfirm, setClearAllConfirm] = useState(false)
  const [clearBusy, setClearBusy] = useState(false)

  const [shareFeedback, setShareFeedback] = useState<string | null>(null)

  // —— 提醒配置（loadReminders 访问 localStorage，须在客户端 effect 中加载）——
  const [reminders, setReminders] = useState<ReminderConfig | null>(null)
  useEffect(() => {
    // eslint-disable-next-line react-hooks/set-state-in-effect -- 客户端 localStorage 初始化
    setReminders(loadReminders())
  }, [])

  useEffect(() => {
    let cancelled = false
    async function loadCounts() {
      const counts = await countAllRecords()
      if (!cancelled) setRecordCounts(counts)
    }
    loadCounts()
    return () => {
      cancelled = true
    }
  }, [])

  async function handleShare() {
    setShareFeedback(null)
    const { origin, pathname } = window.location
    const url = `${origin}${pathname}`
    const text = `${t('settings.shareText')} ${url}`
    if (navigator.share) {
      try {
        await navigator.share({ title: t('settings.shareTitle'), text, url })
        return
      } catch (e) {
        if ((e as Error)?.name === 'AbortError') return
      }
    }
    try {
      await navigator.clipboard.writeText(text)
      setShareFeedback(t('common.copied'))
    } catch {
      try {
        const ta = document.createElement('textarea')
        ta.value = text
        ta.style.position = 'fixed'
        ta.style.opacity = '0'
        document.body.appendChild(ta)
        ta.select()
        document.execCommand('copy')
        document.body.removeChild(ta)
        setShareFeedback(t('common.copied'))
      } catch {
        setShareFeedback(`${t('settings.shareFallback')} ${url}`)
      }
    }
    window.setTimeout(() => setShareFeedback(null), 3000)
  }

  async function requestNotificationPermission(): Promise<boolean> {
    if (!('Notification' in window)) return false
    if (Notification.permission === 'granted') return true
    if (Notification.permission === 'default') {
      try {
        const p = await Notification.requestPermission()
        return p === 'granted'
      } catch {
        return false
      }
    }
    return false
  }

  async function toggleReminder(type: ReminderType) {
    if (!reminders) return
    const next: ReminderConfig = {
      ...reminders,
      [type]: { ...reminders[type], enabled: !reminders[type].enabled },
    }
    setReminders(next)
    if (next[type].enabled) await requestNotificationPermission()
    saveReminders(next)
  }

  function persistReminders() {
    if (reminders) saveReminders(reminders)
  }

  function setIntervalReminder(type: 'feed' | 'medication' | 'diaper' | 'sleep', v: number | string) {
    if (!reminders) return
    const hours = typeof v === 'number' ? v : Number(v)
    setReminders({ ...reminders, [type]: { ...reminders[type], intervalHours: hours } })
  }

  function setSleepTime(v: number | string) {
    if (!reminders) return
    setReminders({ ...reminders, sleep: { ...reminders.sleep, time: String(v) } })
  }

  const reminderRows = useMemo(
    () => [
      { type: 'feed' as const, title: t('reminders.feed.title'), sub: t('reminders.feed.sub') },
      { type: 'sleep' as const, title: t('reminders.sleep.title'), sub: t('reminders.sleep.sub') },
      { type: 'medication' as const, title: t('reminders.medication.title'), sub: t('reminders.medication.sub') },
      { type: 'vaccination' as const, title: t('reminders.vaccination.title'), sub: t('reminders.vaccination.sub') },
      { type: 'diaper' as const, title: t('reminders.diaper.title'), sub: t('reminders.diaper.sub') },
    ],
    [t],
  )

  function openAddBaby() {
    setBabyName('')
    setBabyGender('')
    setBabyBirthDate('')
    setBabyAvatar('')
    setBabyModal({ mode: 'add' })
  }

  function openEditBaby(b: Baby) {
    setBabyName(b.name)
    setBabyGender(b.gender ?? '')
    setBabyBirthDate(b.birthDate ?? '')
    setBabyAvatar(b.avatar ?? '')
    setBabyModal({ mode: 'edit', id: b.id })
  }

  async function saveBaby() {
    const name = babyName.trim()
    if (!name || !babyBirthDate) return
    if (babyModal?.mode === 'add' && !babyGender) return
    if (babyModal?.mode === 'edit' && babyModal.id != null) {
      await db.babies.update(babyModal.id, {
        name,
        gender: babyGender || undefined,
        birthDate: babyBirthDate,
        avatar: babyAvatar || undefined,
      })
    } else {
      await addBaby(name, babyGender || undefined, babyBirthDate, undefined, undefined, babyAvatar || undefined)
    }
    setBabyModal(null)
  }

  async function confirmDeleteBaby() {
    const id = deleteBabyConfirm?.id
    if (id == null) return
    await clearBabyData(id)
    await db.babies.delete(id)
    if (activeBabyId === id) setActiveBabyId(null)
    setDeleteBabyConfirm(null)
  }

  function babyAge(b: Baby): string {
    if (!b.birthDate) return t('settings.noBirthDate')
    // eslint-disable-next-line react-hooks/purity -- 年龄计算依赖当前时刻，渲染时读取即可
    const diff = Date.now() - new Date(b.birthDate + 'T00:00:00').getTime()
    if (diff < 0) return t('settings.birthdayUpcoming')
    const months = Math.floor(diff / (1000 * 60 * 60 * 24 * 30.44))
    if (months < 1) {
      const days = Math.floor(diff / (1000 * 60 * 60 * 24))
      return t('settings.ageDays', { n: days })
    }
    if (months < 12) return t('settings.ageMonths', { n: months })
    const years = Math.floor(months / 12)
    return t('settings.ageYears', { years, months: months % 12 })
  }

  async function handleExportBabyCsv() {
    if (!activeBaby) return
    await exportBabyCsvs(activeBaby)
    setExportSuccess(true)
    setTimeout(() => setExportSuccess(false), 3000)
  }

  async function handleExportAllCsv() {
    await exportAllBabiesCsv()
    setExportSuccess(true)
    setTimeout(() => setExportSuccess(false), 3000)
  }

  async function handleImportFile(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0]
    if (!file) return
    setImportBusy(true)
    try {
      const result = await importAllCsv(file)
      alert(
        t('settings.importSuccess', {
          babies: result.babies,
          feedings: result.feedings,
          diapers: result.diapers,
          pumpings: result.pumpings,
          sleeps: result.sleeps,
          growths: result.growths,
          solidFoods: result.solidFoods,
          medications: result.medications,
          vaccinations: result.vaccinations,
          temperatures: result.temperatures,
          milestones: result.milestones,
        }),
      )
      setRecordCounts(await countAllRecords())
    } catch {
      alert(t('settings.importFailed'))
    } finally {
      setImportBusy(false)
      if (importFileRef.current) importFileRef.current.value = ''
    }
  }

  async function confirmClearAll() {
    setClearBusy(true)
    try {
      await clearAllData()
      setActiveBabyId(null)
      localStorage.removeItem('babysitter.activeBabyId')
      setRecordCounts({
        feedings: 0,
        diapers: 0,
        pumpings: 0,
        sleeps: 0,
        growths: 0,
        solidFoods: 0,
        medications: 0,
        vaccinations: 0,
        temperatures: 0,
        milestones: 0,
      })
      setClearAllConfirm(false)
    } finally {
      setClearBusy(false)
    }
  }

  return (
    <div className={`page ${s['settings-page']}`}>
      <PageHeader />

      {/* 宝宝管理 */}
      <p className="section-title">{t('settings.babyManage')}</p>
      <div className="card">
        <div className={s['baby-list']}>
          {babies.map((b) => (
            <div
              key={b.id}
              className={`${s['baby-item']} ${b.id === activeBabyId ? s.active : ''}`}
              onClick={() => b.id != null && setActiveBabyId(b.id)}
            >
              <div className={s['baby-avatar']} style={{ background: b.avatarColor }}>
                {b.avatar ?? b.name[0]}
              </div>
              <div className={s['baby-info']}>
                <p className={s['baby-name']}>
                  {b.name}
                  {b.id === activeBabyId ? t('common.current') : ''}
                </p>
                <p className={s['baby-meta']}>
                  {b.gender
                    ? t(b.gender === 'boy' ? 'settings.genderBoy' : 'settings.genderGirl')
                    : t('settings.genderUnknown')}
                  · {babyAge(b)}
                </p>
              </div>
              <div className={s['baby-actions']}>
                <button
                  className={s['icon-btn']}
                  title={t('common.edit')}
                  onClick={(e) => {
                    e.stopPropagation()
                    openEditBaby(b)
                  }}
                >
                  ✏️
                </button>
                <button
                  className={s['icon-btn']}
                  title={t('common.delete')}
                  onClick={(e) => {
                    e.stopPropagation()
                    setDeleteBabyConfirm(b)
                  }}
                >
                  🗑️
                </button>
              </div>
            </div>
          ))}
        </div>
        <button className="btn btn-outline btn-block" onClick={openAddBaby}>
          + {t('settings.addBaby')}
        </button>
      </div>

      {/* 提醒设置 */}
      <p className="section-title">{t('settings.reminderSectionTitle')}</p>
      <div className="card">
        <p className={s['data-tip']}>{t('settings.reminderTip')}</p>
        {reminders &&
          reminderRows.map((r) => (
            <div key={r.type} className={s['reminder-block']}>
              <div className={s['reminder-row']}>
                <div className={s['reminder-info']}>
                  <p className={s['reminder-title']}>{r.title}</p>
                  <p className={s['reminder-sub']}>{r.sub}</p>
                </div>
                <button
                  className={`${s.switch} ${reminders[r.type].enabled ? s.on : ''}`}
                  role="switch"
                  aria-checked={reminders[r.type].enabled}
                  onClick={() => toggleReminder(r.type)}
                >
                  <span className={s['switch-knob']} />
                </button>
              </div>
              {reminders[r.type].enabled && r.type !== 'vaccination' && (
                <div className={s['reminder-param']}>
                  {r.type === 'feed' && (
                    <ReminderParam
                      mode="interval"
                      label={t('reminders.intervalLabel')}
                      value={reminders.feed.intervalHours}
                      min={0}
                      step={0.5}
                      placeholder={t('reminders.intervalPh', { n: '2.5' })}
                      hint={t('reminders.feed.hint')}
                      onValueChange={(v) => setIntervalReminder('feed', v)}
                      onChange={persistReminders}
                    />
                  )}
                  {r.type === 'sleep' && (
                    <ReminderParam
                      mode="time"
                      label={t('reminders.sleepTimeLabel')}
                      value={reminders.sleep.time}
                      placeholder={t('common.selectTime')}
                      onValueChange={setSleepTime}
                      onChange={persistReminders}
                    />
                  )}
                  {r.type === 'sleep' && reminders.sleep.enabled && (
                    <ReminderParam
                      mode="interval"
                      label={t('reminders.intervalLabel')}
                      value={reminders.sleep.intervalHours}
                      min={0}
                      step={1}
                      placeholder={t('reminders.intervalPh', { n: '4' })}
                      hint={t('reminders.sleep.hint')}
                      onValueChange={(v) => setIntervalReminder('sleep', v)}
                      onChange={persistReminders}
                    />
                  )}
                  {r.type === 'medication' && (
                    <ReminderParam
                      mode="interval"
                      label={t('reminders.intervalLabel')}
                      value={reminders.medication.intervalHours}
                      min={1}
                      step={1}
                      placeholder={t('reminders.intervalPh', { n: '6' })}
                      hint={t('reminders.medication.hint')}
                      onValueChange={(v) => setIntervalReminder('medication', v)}
                      onChange={persistReminders}
                    />
                  )}
                  {r.type === 'diaper' && (
                    <ReminderParam
                      mode="interval"
                      label={t('reminders.intervalLabel')}
                      value={reminders.diaper.intervalHours}
                      min={1}
                      step={1}
                      placeholder={t('reminders.intervalPh', { n: '6' })}
                      hint={t('reminders.diaper.hint')}
                      onValueChange={(v) => setIntervalReminder('diaper', v)}
                      onChange={persistReminders}
                    />
                  )}
                </div>
              )}
            </div>
          ))}
      </div>

      {/* 分享给朋友 */}
      <p className="section-title">{t('settings.shareSection')}</p>
      <div className="card">
        <p className={s['data-tip']}>{t('settings.shareTip')}</p>
        <button className="btn btn-primary btn-block" onClick={handleShare}>
          {t('settings.shareBtn')}
        </button>
        {shareFeedback && <p className={s['export-ok']}>{shareFeedback}</p>}
      </div>

      {/* 数据管理 */}
      <p className="section-title">{t('settings.dataManage')}</p>
      <div className="card">
        <p className={s['data-tip']}>{t('settings.dataTip')}</p>
        <div className={s['data-counts']}>
          <span>
            {t('log.filters.feeding')} {t('common.records', { n: recordCounts.feedings })}
          </span>
          <span>
            {t('log.filters.diaper')} {t('common.records', { n: recordCounts.diapers })}
          </span>
          <span>
            {t('log.filters.pumping')} {t('common.records', { n: recordCounts.pumpings })}
          </span>
          <span>
            {t('log.filters.sleep')} {t('common.records', { n: recordCounts.sleeps })}
          </span>
          <span>
            {t('log.filters.growth')} {t('common.records', { n: recordCounts.growths })}
          </span>
          <span>
            {t('log.filters.solidFood')} {t('common.records', { n: recordCounts.solidFoods })}
          </span>
          <span>
            {t('log.filters.medication')} {t('common.records', { n: recordCounts.medications })}
          </span>
          <span>
            {t('log.filters.vaccination')} {t('common.records', { n: recordCounts.vaccinations })}
          </span>
          <span>
            {t('log.filters.temperature')} {t('common.records', { n: recordCounts.temperatures })}
          </span>
          <span>
            {t('log.filters.milestone')} {t('common.records', { n: recordCounts.milestones })}
          </span>
        </div>
        <div className={s['data-actions']}>
          <button className="btn btn-primary btn-block" disabled={!activeBaby} onClick={handleExportBabyCsv}>
            <span className={s['btn-label']}>
              {activeBaby ? t('settings.exportBabyCsv', { name: activeBaby.name }) : t('common.noBaby')}
            </span>
          </button>
          <button className="btn btn-outline btn-block" onClick={handleExportAllCsv}>
            {t('settings.exportAllCsv')}
          </button>
          <button className="btn btn-outline btn-block" disabled={importBusy} onClick={() => importFileRef.current?.click()}>
            {importBusy ? t('common.importing') : t('common.importCsv')}
          </button>
          <input ref={importFileRef} type="file" accept=".csv,text/csv" hidden onChange={handleImportFile} />
          {exportSuccess && <p className={s['export-ok']}>{t('settings.exportOk')}</p>}
          <button className="btn btn-danger-soft btn-block" onClick={() => setClearAllConfirm(true)}>
            {t('settings.clearAll')}
          </button>
        </div>
      </div>

      {/* 关于 */}
      <p className="section-title">{t('settings.about')}</p>
      <div className="card">
        <p className={s['about-text']}>{t('settings.aboutText1')}</p>
        <p className={s['about-text']}>{t('settings.aboutText2')}</p>
        <p className={s['about-text']}>{t('settings.aboutText3')}</p>
        <p className={`${s['about-text']} ${s.muted}`}>{t('settings.aboutMuted')}</p>
      </div>

      {/* 宝宝编辑弹窗 */}
      <BaseModal
        show={babyModal !== null}
        title={babyModal?.mode === 'edit' ? t('settings.editBaby') : t('settings.addBaby')}
        onClose={() => setBabyModal(null)}
      >
        <div className="form-field">
          <label className="form-label">{t('settings.babyName')} *</label>
          <input
            value={babyName}
            type="text"
            placeholder={t('settings.babyNamePh')}
            className="form-input"
            onChange={(e) => setBabyName(e.target.value)}
          />
        </div>
        <div className="form-field">
          <label className="form-label">
            {t('settings.genderLabel')} {babyModal?.mode === 'add' ? '*' : ''}
          </label>
          <div className={s['gender-picker']} role="radiogroup">
            <button
              type="button"
              className={`${s['gender-option']} ${babyGender === 'boy' ? s.selected : ''}`}
              aria-checked={babyGender === 'boy'}
              role="radio"
              onClick={() => setBabyGender('boy')}
            >
              <span className={s['gender-emoji']}>👦</span>
              {t('settings.genderBoy')}
            </button>
            <button
              type="button"
              className={`${s['gender-option']} ${babyGender === 'girl' ? s.selected : ''}`}
              aria-checked={babyGender === 'girl'}
              role="radio"
              onClick={() => setBabyGender('girl')}
            >
              <span className={s['gender-emoji']}>👧</span>
              {t('settings.genderGirl')}
            </button>
          </div>
        </div>
        <div className="form-field">
          <label className="form-label">{t('settings.birthDate')} *</label>
          <input
            value={babyBirthDate}
            type="date"
            placeholder={t('common.selectDate')}
            className="form-input"
            onChange={(e) => setBabyBirthDate(e.target.value)}
          />
        </div>
        <div className="form-field">
          <label className="form-label">{t('settings.avatarLabel')}</label>
          <div className="avatar-picker">
            {BABY_AVATARS.map((a) => (
              <button
                key={a}
                type="button"
                className={`${s['avatar-option']} ${babyAvatar === a ? s.selected : ''}`}
                onClick={() => setBabyAvatar(a)}
              >
                {a}
              </button>
            ))}
          </div>
        </div>
        <div className="form-actions">
          <button className="btn btn-outline" onClick={() => setBabyModal(null)}>
            {t('common.cancel')}
          </button>
          <button
            className="btn btn-primary"
            disabled={!babyName.trim() || !babyBirthDate || (babyModal?.mode === 'add' && !babyGender)}
            onClick={saveBaby}
          >
            {t('settings.saveBaby')}
          </button>
        </div>
      </BaseModal>

      {/* 删除宝宝确认 */}
      <BaseModal
        show={deleteBabyConfirm !== null}
        title={t('settings.deleteBabyTitle')}
        onClose={() => setDeleteBabyConfirm(null)}
      >
        <p className={s['confirm-text']}>{t('settings.deleteBabyText', { name: deleteBabyConfirm?.name ?? '' })}</p>
        <div className="form-actions">
          <button className="btn btn-outline" onClick={() => setDeleteBabyConfirm(null)}>
            {t('common.cancel')}
          </button>
          <button className="btn btn-danger-soft" onClick={confirmDeleteBaby}>
            {t('log.confirmDelete')}
          </button>
        </div>
      </BaseModal>

      {/* 清空数据确认 */}
      <BaseModal show={clearAllConfirm} title={t('settings.clearConfirmTitle')} onClose={() => setClearAllConfirm(false)}>
        <p className={s['confirm-text']}>{t('settings.clearConfirmText')}</p>
        <div className="form-actions">
          <button className="btn btn-outline" onClick={() => setClearAllConfirm(false)}>
            {t('common.cancel')}
          </button>
          <button className="btn btn-danger-soft" disabled={clearBusy} onClick={confirmClearAll}>
            {t('settings.confirmClear')}
          </button>
        </div>
      </BaseModal>
    </div>
  )
}
