// src/views/StatsView.tsx
'use client'

import { useEffect, useMemo, useState } from 'react'
import { useTranslation } from 'react-i18next'
import type { EChartsOption } from 'echarts'
import { useLiveQuery } from 'dexie-react-hooks'
import PageHeader from '@/components/common/PageHeader'
import ChartCard from '@/components/charts/ChartCard'
import GrowthCurveCharts from '@/components/charts/GrowthCurveCharts'
import { db } from '@/db'
import { useBabies } from '@/stores/baby'
import {
  buildDailySeries,
  aggregateRange,
  compareRanges,
  RANGE_PRESETS,
  type DayAggregate,
  type ComparisonResult,
} from '@/services/stats'
import { CHART_COLORS, MS_PER_DAY } from '@/constants'
import { formatDuration, formatPercentChange, formatAmount, startOfDay } from '@/utils/format'
import { useChartTheme } from '@/hooks/useChartTheme'
import type {
  Feeding,
  DiaperChange,
  Pumping,
  Sleep,
  GrowthRecord,
  SolidFood,
  Medication,
  Temperature,
} from '@/types'
import s from './StatsView.module.css'

export default function StatsView() {
  const { t } = useTranslation()
  const { activeBabyId, activeBaby } = useBabies()
  const { axisColor, axisLineColor, splitLineColor } = useChartTheme()

  useEffect(() => {
    document.title = `${t('nav.stats')} · ${t('app.name')}`
  }, [t])

  const [now, setNow] = useState(() => Date.now())
  useEffect(() => {
    const nowTimer = window.setInterval(() => setNow(Date.now()), 60_000)
    return () => window.clearInterval(nowTimer)
  }, [])

  // 时间范围选择
  const [rangeKey, setRangeKey] = useState('7d')
  const range = RANGE_PRESETS.find((p) => p.key === rangeKey) ?? RANGE_PRESETS[1]!

  // 概览 tab：对比 / 汇总
  const [activeView, setActiveView] = useState<'summary' | 'trend' | 'compare'>('summary')

  // —— 数据查询（按当前宝宝）——
  const feedingsResult = useLiveQuery(
    async () => {
      if (activeBabyId == null) return [] as Feeding[]
      return db.feedings
        .where('[babyId+startTime]')
        .between([activeBabyId, 0], [activeBabyId, Number.MAX_SAFE_INTEGER])
        .toArray()
    },
    [activeBabyId],
    [] as Feeding[],
  )
  const feedings = useMemo(() => feedingsResult ?? [], [feedingsResult])

  const diapersResult = useLiveQuery(
    async () => {
      if (activeBabyId == null) return [] as DiaperChange[]
      return db.diapers
        .where('[babyId+time]')
        .between([activeBabyId, 0], [activeBabyId, Number.MAX_SAFE_INTEGER])
        .toArray()
    },
    [activeBabyId],
    [] as DiaperChange[],
  )
  const diapers = useMemo(() => diapersResult ?? [], [diapersResult])

  const pumpingsResult = useLiveQuery(
    async () => {
      if (activeBabyId == null) return [] as Pumping[]
      return db.pumpings
        .where('[babyId+startTime]')
        .between([activeBabyId, 0], [activeBabyId, Number.MAX_SAFE_INTEGER])
        .toArray()
    },
    [activeBabyId],
    [] as Pumping[],
  )
  const pumpings = useMemo(() => pumpingsResult ?? [], [pumpingsResult])

  const sleepsResult = useLiveQuery(
    async () => {
      if (activeBabyId == null) return [] as Sleep[]
      return db.sleeps
        .where('[babyId+startTime]')
        .between([activeBabyId, 0], [activeBabyId, Number.MAX_SAFE_INTEGER])
        .toArray()
    },
    [activeBabyId],
    [] as Sleep[],
  )
  const sleeps = useMemo(() => sleepsResult ?? [], [sleepsResult])

  const growthsResult = useLiveQuery(
    async () => {
      if (activeBabyId == null) return [] as GrowthRecord[]
      return db.growths
        .where('[babyId+date]')
        .between([activeBabyId, 0], [activeBabyId, Number.MAX_SAFE_INTEGER])
        .toArray()
    },
    [activeBabyId],
    [] as GrowthRecord[],
  )
  const growths = useMemo(() => growthsResult ?? [], [growthsResult])

  const solidFoodsResult = useLiveQuery(
    async () => {
      if (activeBabyId == null) return [] as SolidFood[]
      return db.solidFoods
        .where('[babyId+time]')
        .between([activeBabyId, 0], [activeBabyId, Number.MAX_SAFE_INTEGER])
        .toArray()
    },
    [activeBabyId],
    [] as SolidFood[],
  )
  const solidFoods = useMemo(() => solidFoodsResult ?? [], [solidFoodsResult])

  const medicationsResult = useLiveQuery(
    async () => {
      if (activeBabyId == null) return [] as Medication[]
      return db.medications
        .where('[babyId+time]')
        .between([activeBabyId, 0], [activeBabyId, Number.MAX_SAFE_INTEGER])
        .toArray()
    },
    [activeBabyId],
    [] as Medication[],
  )
  const medications = useMemo(() => medicationsResult ?? [], [medicationsResult])

  const temperaturesResult = useLiveQuery(
    async () => {
      if (activeBabyId == null) return [] as Temperature[]
      return db.temperatures
        .where('[babyId+time]')
        .between([activeBabyId, 0], [activeBabyId, Number.MAX_SAFE_INTEGER])
        .toArray()
    },
    [activeBabyId],
    [] as Temperature[],
  )
  const temperatures = useMemo(() => temperaturesResult ?? [], [temperaturesResult])

  // “全部”按实际最早记录收窄，避免从 1970 起逐日建桶导致日均失真
  const allDataStart = useMemo(() => {
    if (rangeKey !== 'all') return null
    const stamps = [
      ...feedings.map((f) => f.startTime),
      ...diapers.map((d) => d.time),
      ...pumpings.map((p) => p.startTime),
      ...sleeps.map((s) => s.startTime),
      ...growths.map((g) => g.date),
      ...solidFoods.map((sf) => sf.time),
      ...medications.map((m) => m.time),
      ...temperatures.map((tp) => tp.time),
    ].filter((ts) => Number.isFinite(ts) && ts > 0)
    if (stamps.length === 0) return startOfDay(now) - 30 * MS_PER_DAY
    return startOfDay(Math.min(...stamps))
  }, [rangeKey, feedings, diapers, pumpings, sleeps, growths, solidFoods, medications, temperatures, now])

  const rangeStart = useMemo(() => {
    if (rangeKey === 'all') return allDataStart ?? startOfDay(now) - 30 * MS_PER_DAY
    return range.getRange(now)[0]
  }, [rangeKey, allDataStart, range, now])

  const rangeEnd = useMemo(() => {
    if (rangeKey === 'all') return startOfDay(now) + MS_PER_DAY
    return range.getRange(now)[1]
  }, [rangeKey, range, now])

  // 每日序列（趋势图数据）
  const days = useMemo<DayAggregate[]>(
    () =>
      buildDailySeries(
        feedings,
        diapers,
        pumpings,
        sleeps,
        rangeStart,
        rangeEnd,
        solidFoods,
        medications,
        temperatures,
      ),
    [feedings, diapers, pumpings, sleeps, rangeStart, rangeEnd, solidFoods, medications, temperatures],
  )

  // 当前区间 vs 上一等长区间（对比）
  const previousStart = useMemo(() => rangeStart - (rangeEnd - rangeStart), [rangeStart, rangeEnd])
  const currentAgg = useMemo(
    () =>
      aggregateRange(
        feedings,
        diapers,
        pumpings,
        sleeps,
        rangeStart,
        rangeEnd,
        solidFoods,
        medications,
        temperatures,
      ),
    [feedings, diapers, pumpings, sleeps, rangeStart, rangeEnd, solidFoods, medications, temperatures],
  )
  const previousAgg = useMemo(
    () =>
      aggregateRange(
        feedings,
        diapers,
        pumpings,
        sleeps,
        previousStart,
        rangeStart,
        solidFoods,
        medications,
        temperatures,
      ),
    [feedings, diapers, pumpings, sleeps, previousStart, rangeStart, solidFoods, medications, temperatures],
  )
  const comparisons = useMemo<ComparisonResult[]>(() => compareRanges(currentAgg, previousAgg), [currentAgg, previousAgg])

  // 格式化轴标签
  const xLabels = useMemo(() => days.map((d) => d.date.slice(5).replace('-', '/')), [days])
  const yFormatter = (v: number) => (v >= 1000 ? `${(v / 1000).toFixed(1)}k` : String(v))

  /** 趋势图 tooltip：显示日期 + 各系列数值（无数据日显示 -），触摸/悬停均可查看 */
  const trendTooltip = (fmt: (v: number) => string) => ({
    trigger: 'axis' as const,
    formatter: (params: unknown) => {
      const list = params as Array<{ seriesName: string; marker: string; value?: number | null; axisValue?: string }>
      const first = list.find((p) => typeof p.value === 'number' && !Number.isNaN(p.value))
      if (!first) return ''
      const dateStr = first.axisValue ?? ''
      const lines = list.map((p) => {
        const v = typeof p.value === 'number' ? p.value : null
        return `${p.marker}${p.seriesName}: ${v != null ? fmt(v) : '-'}`
      })
      return `<b>${dateStr}</b><br/>${lines.join('<br/>')}`
    },
  })

  // —— 趋势图配置 ——
  const milkOption = useMemo<EChartsOption>(
    () => ({
      tooltip: trendTooltip((v) => `${Math.round(v)} ml`),
      grid: { left: 44, right: 16, top: 12, bottom: 28 },
      xAxis: {
        type: 'category',
        data: xLabels,
        axisLabel: { color: axisColor, fontSize: 10, hideOverlap: true },
        axisLine: { lineStyle: { color: axisLineColor } },
      },
      yAxis: {
        type: 'value',
        axisLabel: { color: axisColor, fontSize: 10, formatter: yFormatter, hideOverlap: true },
        splitLine: { lineStyle: { color: splitLineColor } },
      },
      series: [
        {
          name: t('stats.series.milk'),
          type: 'line',
          smooth: true,
          symbol: 'circle',
          symbolSize: 5,
          data: days.map((d) => d.totalMilkAmount),
          lineStyle: { width: 2.5, color: CHART_COLORS.feedAmount },
          itemStyle: { color: CHART_COLORS.feedAmount },
          areaStyle: {
            color: {
              type: 'linear',
              x: 0,
              y: 0,
              x2: 0,
              y2: 1,
              colorStops: [
                { offset: 0, color: 'rgba(232,144,108,0.25)' },
                { offset: 1, color: 'rgba(232,144,108,0.02)' },
              ],
            },
          },
        },
      ],
    }),
     
    [xLabels, axisColor, axisLineColor, splitLineColor, days, t],
  )

  const sleepOption = useMemo<EChartsOption>(
    () => ({
      tooltip: trendTooltip((v) => `${v} h`),
      grid: { left: 44, right: 16, top: 12, bottom: 28 },
      xAxis: {
        type: 'category',
        data: xLabels,
        axisLabel: { color: axisColor, fontSize: 10, hideOverlap: true },
        axisLine: { lineStyle: { color: axisLineColor } },
      },
      yAxis: {
        type: 'value',
        axisLabel: { color: axisColor, fontSize: 10, hideOverlap: true },
        splitLine: { lineStyle: { color: splitLineColor } },
      },
      series: [
        {
          name: t('stats.series.sleep'),
          type: 'bar',
          barMaxWidth: 22,
          data: days.map((d) => +(d.sleepMs / 3600_000).toFixed(1)),
          itemStyle: { color: CHART_COLORS.sleep, borderRadius: [4, 4, 0, 0] },
        },
      ],
    }),
     
    [xLabels, axisColor, axisLineColor, splitLineColor, days, t],
  )

  const diaperOption = useMemo<EChartsOption>(
    () => ({
      tooltip: trendTooltip((v) => t('common.times', { n: Math.round(v) })),
      grid: { left: 44, right: 16, top: 12, bottom: 28 },
      xAxis: {
        type: 'category',
        data: xLabels,
        axisLabel: { color: axisColor, fontSize: 10, hideOverlap: true },
        axisLine: { lineStyle: { color: axisLineColor } },
      },
      yAxis: {
        type: 'value',
        axisLabel: { color: axisColor, fontSize: 10, hideOverlap: true },
        splitLine: { lineStyle: { color: splitLineColor } },
      },
      series: [
        {
          name: t('stats.series.wet'),
          type: 'bar',
          stack: 'diaper',
          barMaxWidth: 22,
          data: days.map((d) => d.wetCount),
          itemStyle: { color: '#8FB9D8' },
        },
        {
          name: t('stats.series.dirty'),
          type: 'bar',
          stack: 'diaper',
          barMaxWidth: 22,
          data: days.map((d) => d.dirtyCount),
          itemStyle: { color: '#B58B62' },
        },
      ],
    }),
     
    [xLabels, axisColor, axisLineColor, splitLineColor, days, t],
  )

  const pumpOption = useMemo<EChartsOption>(
    () => ({
      tooltip: trendTooltip((v) => `${Math.round(v)} ml`),
      grid: { left: 44, right: 16, top: 12, bottom: 28 },
      xAxis: {
        type: 'category',
        data: xLabels,
        axisLabel: { color: axisColor, fontSize: 10, hideOverlap: true },
        axisLine: { lineStyle: { color: axisLineColor } },
      },
      yAxis: {
        type: 'value',
        axisLabel: { color: axisColor, fontSize: 10, formatter: yFormatter, hideOverlap: true },
        splitLine: { lineStyle: { color: splitLineColor } },
      },
      series: [
        {
          name: t('stats.series.pump'),
          type: 'line',
          smooth: true,
          symbol: 'circle',
          symbolSize: 5,
          data: days.map((d) => d.pumpAmount),
          lineStyle: { width: 2.5, color: CHART_COLORS.pump },
          itemStyle: { color: CHART_COLORS.pump },
          areaStyle: {
            color: {
              type: 'linear',
              x: 0,
              y: 0,
              x2: 0,
              y2: 1,
              colorStops: [
                { offset: 0, color: 'rgba(216,168,200,0.25)' },
                { offset: 1, color: 'rgba(216,168,200,0.02)' },
              ],
            },
          },
        },
      ],
    }),
     
    [xLabels, axisColor, axisLineColor, splitLineColor, days, t],
  )

  const temperatureOption = useMemo<EChartsOption>(
    () => ({
      tooltip: trendTooltip((v) => `${v} ℃`),
      grid: { left: 44, right: 16, top: 12, bottom: 28 },
      xAxis: {
        type: 'category',
        data: xLabels,
        axisLabel: { color: axisColor, fontSize: 10, hideOverlap: true },
        axisLine: { lineStyle: { color: axisLineColor } },
      },
      yAxis: {
        type: 'value',
        min: 35,
        max: 40,
        axisLabel: { color: axisColor, fontSize: 10, formatter: (v: number) => `${v}℃`, hideOverlap: true },
        splitLine: { lineStyle: { color: splitLineColor } },
      },
      series: [
        {
          name: t('stats.series.temperature'),
          type: 'line',
          smooth: true,
          symbol: 'circle',
          symbolSize: 6,
          data: days.map((d) => (d.temperatureCount > 0 ? +d.temperatureAvg.toFixed(1) : null)),
          connectNulls: false,
          lineStyle: { width: 2.5, color: CHART_COLORS.temperature },
          itemStyle: { color: CHART_COLORS.temperature },
          markLine: {
            silent: true,
            symbol: 'none',
            label: { show: false },
            data: [{ yAxis: 37.3 }],
            lineStyle: { color: '#ff7a45', type: 'dashed', width: 1 },
          },
        },
      ],
    }),
     
    [xLabels, axisColor, axisLineColor, splitLineColor, days, t],
  )

  // 对比面板格式化
  function formatComparisonValue(c: ComparisonResult, value: number): string {
    if (c.key === 'sleepMs') return formatDuration(value)
    if (
      c.key === 'totalMilkAmount' ||
      c.key === 'breastMilkAmount' ||
      c.key === 'formulaAmount' ||
      c.key === 'pumpAmount'
    ) {
      return `${Math.round(value)} ml`
    }
    return t('common.times', { n: Math.round(value) })
  }

  const rangeLabel = t(range.label)

  // —— 区间汇总（周报/月报）——
  const summaryDays = Math.max(1, currentAgg.dayCount)
  const rangeGrowthCount = growths.filter((g) => g.date >= rangeStart && g.date < rangeEnd).length

  const summaryItems = useMemo(() => {
    const agg = currentAgg
    const daysCount = summaryDays
    return [
      {
        label: t('stats.summary.feedCount'),
        value: t('common.times', { n: agg.feedCount }),
        sub: t('common.daily', { value: t('common.times', { n: (agg.feedCount / daysCount).toFixed(1) }) }),
      },
      {
        label: t('stats.summary.totalMilk'),
        value: formatAmount(agg.totalMilkAmount),
        sub: t('common.daily', { value: formatAmount(agg.totalMilkAmount / daysCount) }),
      },
      {
        label: t('stats.summary.breastCount'),
        value: t('common.times', { n: agg.breastCount }),
        sub: t('common.daily', { value: t('common.times', { n: (agg.breastCount / daysCount).toFixed(1) }) }),
      },
      {
        label: t('stats.summary.sleepMs'),
        value: formatDuration(agg.sleepMs),
        sub: t('common.daily', { value: formatDuration(agg.sleepMs / daysCount) }),
      },
      {
        label: t('stats.summary.diaper'),
        value: t('common.times', { n: agg.diaperCount }),
        sub: t('common.daily', { value: t('common.times', { n: (agg.diaperCount / daysCount).toFixed(1) }) }),
      },
      {
        label: t('stats.summary.pumpAmount'),
        value: formatAmount(agg.pumpAmount),
        sub: t('common.daily', { value: formatAmount(agg.pumpAmount / daysCount) }),
      },
      {
        label: t('stats.summary.growthRecords'),
        value: t('common.records', { n: rangeGrowthCount }),
        sub: rangeLabel,
      },
      {
        label: t('stats.summary.solidFood'),
        value: t('common.times', { n: agg.solidFoodCount }),
        sub: t('common.daily', { value: t('common.times', { n: (agg.solidFoodCount / daysCount).toFixed(1) }) }),
      },
      {
        label: t('stats.summary.medication'),
        value: t('common.times', { n: agg.medicationCount }),
        sub: t('common.daily', { value: t('common.times', { n: (agg.medicationCount / daysCount).toFixed(1) }) }),
      },
      {
        label: t('stats.summary.temperature'),
        value: t('common.times', { n: agg.temperatureCount }),
        sub: t('common.daily', { value: t('common.times', { n: (agg.temperatureCount / daysCount).toFixed(1) }) }),
      },
    ]
     
  }, [currentAgg, summaryDays, rangeGrowthCount, rangeLabel, t])

  return (
    <div className="page stats-page">
      <PageHeader />

      {/* 时间范围 */}
      <div className={s['range-select-row']}>
        <label className={s['range-select-label']} htmlFor="range-select">
          {t('stats.rangeLabel')}
        </label>
        <select
          id="range-select"
          value={rangeKey}
          className={`form-input ${s['range-select']}`}
          onChange={(e) => setRangeKey(e.target.value)}
        >
          {RANGE_PRESETS.map((p) => (
            <option key={p.key} value={p.key}>
              {t(p.label)}
            </option>
          ))}
        </select>
      </div>

      {/* 页面级视图切换：总览 / 趋势 / 对比 */}
      <div className={`${s['overview-tabs']} page-tabs`} role="tablist">
        <button
          className={activeView === 'summary' ? `${s['overview-tab']} ${s.active}` : s['overview-tab']}
          role="tab"
          aria-selected={activeView === 'summary'}
          onClick={() => setActiveView('summary')}
        >
          {t('stats.tabSummary')}
        </button>
        <button
          className={activeView === 'trend' ? `${s['overview-tab']} ${s.active}` : s['overview-tab']}
          role="tab"
          aria-selected={activeView === 'trend'}
          onClick={() => setActiveView('trend')}
        >
          {t('stats.tabTrend')}
        </button>
        <button
          className={activeView === 'compare' ? `${s['overview-tab']} ${s.active}` : s['overview-tab']}
          role="tab"
          aria-selected={activeView === 'compare'}
          onClick={() => setActiveView('compare')}
        >
          {t('stats.tabCompare')}
        </button>
      </div>

      {/* 总览：区间汇总 */}
      {activeView === 'summary' && (
        <div className={`card ${s['overview-card']}`}>
          <span className={s['overview-sub']}>{t('stats.summarySub', { n: summaryDays })}</span>
          <div className={s['summary-grid']}>
            {summaryItems.map((item) => (
              <div key={item.label} className={s['summary-item']}>
                <p className={s['summary-label']}>{item.label}</p>
                <p className={s['summary-value']}>{item.value}</p>
                <p className={s['summary-sub']}>{item.sub}</p>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* 趋势：趋势图 + 成长曲线 */}
      {activeView === 'trend' && (
        <>
          <ChartCard
            title={t('stats.charts.milkTitle')}
            subtitle={`${rangeLabel} · ${t('stats.charts.milkSub')}`}
            option={milkOption}
          />
          <ChartCard title={t('stats.charts.sleepTitle')} subtitle={rangeLabel} option={sleepOption} />
          <ChartCard
            title={t('stats.charts.diaperTitle')}
            subtitle={`${rangeLabel} · ${t('stats.charts.diaperSub')}`}
            option={diaperOption}
          />
          <ChartCard title={t('stats.charts.pumpTitle')} subtitle={rangeLabel} option={pumpOption} />
          <ChartCard
            title={t('stats.charts.temperatureTitle')}
            subtitle={`${rangeLabel} · ${t('stats.charts.temperatureSub')}`}
            option={temperatureOption}
          />

          {/* 成长曲线 */}
          <p className="section-title">{t('stats.growthSection')}</p>
          <GrowthCurveCharts
            babyName={activeBaby?.name ?? ''}
            gender={activeBaby?.gender}
            birthDate={activeBaby?.birthDate}
            records={growths}
          />

          <p className={s['note-text']}>{t('stats.noteText')}</p>
        </>
      )}

      {/* 对比：与上一周期对比 */}
      {activeView === 'compare' && (
        <div className={`card ${s['overview-card']}`}>
          <span className={s['overview-sub']}>{t('stats.compareSub', { range: rangeLabel })}</span>
          <div className={s['compare-grid']}>
            {comparisons.map((c) => (
              <div key={c.key} className={s['compare-item']}>
                <p className={s['compare-label']}>{t(c.label)}</p>
                <p className={s['compare-value']}>{formatComparisonValue(c, c.current)}</p>
                <div className={s['compare-change-row']}>
                  <span
                    className={`${s['compare-change']} ${
                      c.change === null ? s.none : c.change >= 0 ? s.up : s.down
                    }`}
                  >
                    {c.change === null ? '—' : formatPercentChange(c.change)}
                  </span>
                  <span className={s['compare-prev']}>
                    {formatComparisonValue(c, c.previous)} → {formatComparisonValue(c, c.current)}
                  </span>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  )
}

// src/views/StatsView.vue
<script setup lang="ts">
import { computed, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import type { EChartsOption } from 'echarts'
import PageHeader from '@/components/common/PageHeader.vue'
import ChartCard from '@/components/charts/ChartCard.vue'
import { useBabyStore } from '@/stores/baby'
import { useFeedingStore } from '@/stores/feeding'
import { useDiaperStore } from '@/stores/diaper'
import { usePumpingStore } from '@/stores/pumping'
import { useSleepStore } from '@/stores/sleep'
import { useGrowthStore } from '@/stores/growth'
import { useSolidFoodStore } from '@/stores/solidFood'
import { useMedicationStore } from '@/stores/medication'
import { useTemperatureStore } from '@/stores/temperature'
import {
  buildDailySeries,
  aggregateRange,
  compareRanges,
  RANGE_PRESETS,
  type DayAggregate,
  type ComparisonResult,
} from '@/services/stats'
import { CHART_COLORS } from '@/constants'
import { whoData, ageInMonths } from '@/constants/whoGrowth'
import { formatDuration, formatPercentChange, formatAmount } from '@/utils/format'
import { isDark } from '@/composables/useTheme'

const babyStore = useBabyStore()
const feedingStore = useFeedingStore()
const diaperStore = useDiaperStore()
const pumpingStore = usePumpingStore()
const sleepStore = useSleepStore()
const growthStore = useGrowthStore()
const solidFoodStore = useSolidFoodStore()
const medicationStore = useMedicationStore()
const temperatureStore = useTemperatureStore()

const { t } = useI18n()

// 图表配色跟随主题
const axisColor = computed(() => (isDark.value ? '#b9ab9e' : '#8c7b72'))
const axisLineColor = computed(() => (isDark.value ? '#42372f' : '#f0e2d4'))
const splitLineColor = computed(() => (isDark.value ? '#2b251f' : '#f5ece2'))

const now = ref(Date.now())
setInterval(() => (now.value = Date.now()), 60_000)

// 时间范围选择
const rangeKey = ref('7d')
const range = computed(() => RANGE_PRESETS.find((p) => p.key === rangeKey.value)!)
const rangeStart = computed(() => range.value.getRange(now.value)[0])
const rangeEnd = computed(() => range.value.getRange(now.value)[1])

// 概览 tab：对比 / 汇总
const overviewTab = ref<'compare' | 'summary'>('compare')

// 每日序列（趋势图数据）
const days = computed<DayAggregate[]>(() =>
  buildDailySeries(
    feedingStore.feedings,
    diaperStore.diapers,
    pumpingStore.pumpings,
    sleepStore.sleeps,
    rangeStart.value,
    rangeEnd.value,
    solidFoodStore.solidFoods,
    medicationStore.medications,
    temperatureStore.temperatures,
  ),
)

// 当前区间 vs 上一等长区间（对比）
const previousStart = computed(() => rangeStart.value - (rangeEnd.value - rangeStart.value))
const currentAgg = computed(() =>
  aggregateRange(
    feedingStore.feedings,
    diaperStore.diapers,
    pumpingStore.pumpings,
    sleepStore.sleeps,
    rangeStart.value,
    rangeEnd.value,
    solidFoodStore.solidFoods,
    medicationStore.medications,
    temperatureStore.temperatures,
  ),
)
const previousAgg = computed(() =>
  aggregateRange(
    feedingStore.feedings,
    diaperStore.diapers,
    pumpingStore.pumpings,
    sleepStore.sleeps,
    previousStart.value,
    rangeStart.value,
    solidFoodStore.solidFoods,
    medicationStore.medications,
    temperatureStore.temperatures,
  ),
)
const comparisons = computed<ComparisonResult[]>(() => compareRanges(currentAgg.value, previousAgg.value))

// 格式化轴标签
const xLabels = computed(() => days.value.map((d) => d.date.slice(5).replace('-', '/')))
const yFormatter = (v: number) => (v >= 1000 ? `${(v / 1000).toFixed(1)}k` : String(v))

// —— 趋势图配置 ——
const milkOption = computed<EChartsOption>(() => ({
  grid: { left: 44, right: 16, top: 12, bottom: 28 },
  xAxis: {
    type: 'category',
    data: xLabels.value,
    axisLabel: { color: axisColor.value, fontSize: 10 },
    axisLine: { lineStyle: { color: axisLineColor.value } },
  },
  yAxis: {
    type: 'value',
    axisLabel: { color: '#8c7b72', fontSize: 10, formatter: yFormatter },
    splitLine: { lineStyle: { color: splitLineColor.value } },
  },
  series: [
    {
      name: t('stats.series.milk'),
      type: 'line',
      smooth: true,
      symbol: 'circle',
      symbolSize: 5,
      data: days.value.map((d) => d.totalMilkAmount),
      lineStyle: { width: 2.5, color: CHART_COLORS.feedAmount },
      itemStyle: { color: CHART_COLORS.feedAmount },
      areaStyle: {
        color: {
          type: 'linear',
          x: 0,
          y: 0,
          x2: 0,
          y2: 1,
          colorStops: [
            { offset: 0, color: 'rgba(232,144,108,0.25)' },
            { offset: 1, color: 'rgba(232,144,108,0.02)' },
          ],
        },
      },
    },
  ],
}))

const sleepOption = computed<EChartsOption>(() => ({
  grid: { left: 44, right: 16, top: 12, bottom: 28 },
  xAxis: {
    type: 'category',
    data: xLabels.value,
    axisLabel: { color: axisColor.value, fontSize: 10 },
    axisLine: { lineStyle: { color: axisLineColor.value } },
  },
  yAxis: {
    type: 'value',
    axisLabel: { color: '#8c7b72', fontSize: 10 },
    splitLine: { lineStyle: { color: splitLineColor.value } },
  },
  series: [
    {
      name: t('stats.series.sleep'),
      type: 'bar',
      barMaxWidth: 22,
      data: days.value.map((d) => +(d.sleepMs / 3600_000).toFixed(1)),
      itemStyle: { color: CHART_COLORS.sleep, borderRadius: [4, 4, 0, 0] },
    },
  ],
}))

const diaperOption = computed<EChartsOption>(() => ({
  grid: { left: 44, right: 16, top: 12, bottom: 28 },
  xAxis: {
    type: 'category',
    data: xLabels.value,
    axisLabel: { color: axisColor.value, fontSize: 10 },
    axisLine: { lineStyle: { color: axisLineColor.value } },
  },
  yAxis: {
    type: 'value',
    axisLabel: { color: '#8c7b72', fontSize: 10 },
    splitLine: { lineStyle: { color: splitLineColor.value } },
  },
  series: [
    {
      name: t('stats.series.wet'),
      type: 'bar',
      stack: 'diaper',
      barMaxWidth: 22,
      data: days.value.map((d) => d.wetCount),
      itemStyle: { color: '#8FB9D8' },
    },
    {
      name: t('stats.series.dirty'),
      type: 'bar',
      stack: 'diaper',
      barMaxWidth: 22,
      data: days.value.map((d) => d.dirtyCount),
      itemStyle: { color: '#B58B62' },
    },
  ],
}))

const pumpOption = computed<EChartsOption>(() => ({
  grid: { left: 44, right: 16, top: 12, bottom: 28 },
  xAxis: {
    type: 'category',
    data: xLabels.value,
    axisLabel: { color: axisColor.value, fontSize: 10 },
    axisLine: { lineStyle: { color: axisLineColor.value } },
  },
  yAxis: {
    type: 'value',
    axisLabel: { color: '#8c7b72', fontSize: 10, formatter: yFormatter },
    splitLine: { lineStyle: { color: splitLineColor.value } },
  },
  series: [
    {
      name: t('stats.series.pump'),
      type: 'line',
      smooth: true,
      symbol: 'circle',
      symbolSize: 5,
      data: days.value.map((d) => d.pumpAmount),
      lineStyle: { width: 2.5, color: CHART_COLORS.pump },
      itemStyle: { color: CHART_COLORS.pump },
      areaStyle: {
        color: {
          type: 'linear',
          x: 0,
          y: 0,
          x2: 0,
          y2: 1,
          colorStops: [
            { offset: 0, color: 'rgba(216,168,200,0.25)' },
            { offset: 1, color: 'rgba(216,168,200,0.02)' },
          ],
        },
      },
    },
  ],
}))

const temperatureOption = computed<EChartsOption>(() => ({
  grid: { left: 44, right: 16, top: 12, bottom: 28 },
  xAxis: {
    type: 'category',
    data: xLabels.value,
    axisLabel: { color: axisColor.value, fontSize: 10 },
    axisLine: { lineStyle: { color: axisLineColor.value } },
  },
  yAxis: {
    type: 'value',
    min: 35,
    max: 40,
    axisLabel: { color: '#8c7b72', fontSize: 10, formatter: (v: number) => `${v}℃` },
    splitLine: { lineStyle: { color: splitLineColor.value } },
  },
  series: [
    {
      name: t('stats.series.temperature'),
      type: 'line',
      smooth: true,
      symbol: 'circle',
      symbolSize: 6,
      data: days.value.map((d) => (d.temperatureCount > 0 ? +d.temperatureAvg.toFixed(1) : null)),
      connectNulls: false,
      lineStyle: { width: 2.5, color: CHART_COLORS.temperature },
      itemStyle: { color: CHART_COLORS.temperature },
      markLine: {
        silent: true,
        symbol: 'none',
        label: { show: false },
        data: [{ yAxis: 37.3 }],
        lineStyle: { color: '#D97A52', type: 'dashed', width: 1 },
      },
    },
  ],
}))

// 对比面板格式化
function formatComparisonValue(c: ComparisonResult, value: number): string {
  if (c.key === 'sleepMs') return formatDuration(value)
  if (
    c.key === 'totalMilkAmount' ||
    c.key === 'breastMilkAmount' ||
    c.key === 'formulaAmount' ||
    c.key === 'pumpAmount'
  ) {
    return `${Math.round(value)} ml`
  }
  return t('common.times', { n: Math.round(value) })
}

const rangeLabel = computed(() => t(range.value.label))

// —— 区间汇总（周报/月报）——
const summaryDays = computed(() => Math.max(1, currentAgg.value.dayCount))
const rangeGrowthCount = computed(
  () => growthStore.growths.filter((g) => g.date >= rangeStart.value && g.date <= rangeEnd.value).length,
)

const summaryItems = computed(() => {
  const agg = currentAgg.value
  const days = summaryDays.value
  return [
    {
      label: t('stats.summary.feedCount'),
      value: t('common.times', { n: agg.feedCount }),
      sub: t('common.daily', { value: t('common.times', { n: (agg.feedCount / days).toFixed(1) }) }),
    },
    {
      label: t('stats.summary.totalMilk'),
      value: formatAmount(agg.totalMilkAmount),
      sub: t('common.daily', { value: formatAmount(agg.totalMilkAmount / days) }),
    },
    {
      label: t('stats.summary.breastCount'),
      value: t('common.times', { n: agg.breastCount }),
      sub: t('common.daily', { value: t('common.times', { n: (agg.breastCount / days).toFixed(1) }) }),
    },
    {
      label: t('stats.summary.sleepMs'),
      value: formatDuration(agg.sleepMs),
      sub: t('common.daily', { value: formatDuration(agg.sleepMs / days) }),
    },
    {
      label: t('stats.summary.diaper'),
      value: t('common.times', { n: agg.diaperCount }),
      sub: t('common.daily', { value: t('common.times', { n: (agg.diaperCount / days).toFixed(1) }) }),
    },
    {
      label: t('stats.summary.pumpAmount'),
      value: formatAmount(agg.pumpAmount),
      sub: t('common.daily', { value: formatAmount(agg.pumpAmount / days) }),
    },
    {
      label: t('stats.summary.growthRecords'),
      value: t('common.records', { n: rangeGrowthCount.value }),
      sub: rangeLabel.value,
    },
    {
      label: t('stats.summary.solidFood'),
      value: t('common.times', { n: agg.solidFoodCount }),
      sub: t('common.daily', { value: t('common.times', { n: (agg.solidFoodCount / days).toFixed(1) }) }),
    },
    {
      label: t('stats.summary.medication'),
      value: t('common.times', { n: agg.medicationCount }),
      sub: t('common.daily', { value: t('common.times', { n: (agg.medicationCount / days).toFixed(1) }) }),
    },
    {
      label: t('stats.summary.temperature'),
      value: t('common.times', { n: agg.temperatureCount }),
      sub: t('common.daily', { value: t('common.times', { n: (agg.temperatureCount / days).toFixed(1) }) }),
    },
  ]
})

// —— 成长曲线（体重/身高 + WHO 生长标准参考）——
const activeBaby = computed(() => babyStore.babies.find((b) => b.id === babyStore.activeBabyId))
const growthRecords = computed(() => [...growthStore.growths].sort((a, b) => a.date - b.date))
/** 有出生日期才能换算月龄 */
const hasBirthDate = computed(() => Boolean(activeBaby.value?.birthDate))
const whoPoints = computed(() => whoData(activeBaby.value?.gender))

const weightPoints = computed(() =>
  growthRecords.value
    .filter((g) => g.weight != null)
    .map((g) => ({ month: ageInMonths(activeBaby.value!.birthDate!, g.date), weight: g.weight! }))
    .sort((a, b) => a.month - b.month),
)
const heightPoints = computed(() =>
  growthRecords.value
    .filter((g) => g.height != null)
    .map((g) => ({ month: ageInMonths(activeBaby.value!.birthDate!, g.date), height: g.height! }))
    .sort((a, b) => a.month - b.month),
)
/** 图表横轴上限：至少覆盖已有记录的最大月龄（不低于 24 月） */
const growthXMax = computed(() =>
  Math.max(
    24,
    Math.ceil(Math.max(3, ...weightPoints.value.map((p) => p.month), ...heightPoints.value.map((p) => p.month))),
  ),
)
const hasGrowthData = computed(() => weightPoints.value.length > 0 || heightPoints.value.length > 0)

function whoSeries(field: 'weight' | 'length', key: 'p3' | 'p50' | 'p97'): [number, number][] {
  return whoPoints.value.filter((p) => p.month <= growthXMax.value).map((p) => [p.month, p[field][key]])
}

const growthTooltip = (unit: string) => ({
  trigger: 'axis' as const,
  valueFormatter: (v: unknown) => (Array.isArray(v) ? `${Number(v[1]).toFixed(1)} ${unit}` : `${v} ${unit}`),
})

const weightOption = computed<EChartsOption>(() => ({
  grid: { left: 44, right: 16, top: 12, bottom: 28 },
  xAxis: {
    type: 'value',
    min: 0,
    max: growthXMax.value,
    axisLabel: { color: axisColor.value, fontSize: 10, formatter: (v: number) => `${v}${t('duration.monthShort')}` },
    axisLine: { lineStyle: { color: axisLineColor.value } },
  },
  yAxis: {
    type: 'value',
    scale: true,
    axisLabel: { color: '#8c7b72', fontSize: 10, formatter: (v: number) => `${v}kg` },
    splitLine: { lineStyle: { color: splitLineColor.value } },
  },
  tooltip: growthTooltip('kg'),
  series: [
    {
      name: 'P97',
      type: 'line',
      data: whoSeries('weight', 'p97'),
      symbol: 'none',
      lineStyle: { width: 1, color: '#c4b6a6', type: 'dashed' },
      itemStyle: { color: '#c4b6a6' },
    },
    {
      name: 'P50',
      type: 'line',
      data: whoSeries('weight', 'p50'),
      symbol: 'none',
      lineStyle: { width: 1, color: '#a49482', type: 'dashed' },
      itemStyle: { color: '#a49482' },
    },
    {
      name: 'P3',
      type: 'line',
      data: whoSeries('weight', 'p3'),
      symbol: 'none',
      lineStyle: { width: 1, color: '#c4b6a6', type: 'dashed' },
      itemStyle: { color: '#c4b6a6' },
    },
    {
      name: t('stats.babyWeight'),
      type: 'line',
      data: weightPoints.value.map((p) => [p.month, p.weight]),
      smooth: true,
      symbol: 'circle',
      symbolSize: 7,
      lineStyle: { width: 2.5, color: CHART_COLORS.feedAmount },
      itemStyle: { color: CHART_COLORS.feedAmount },
    },
  ],
}))

const heightOption = computed<EChartsOption>(() => ({
  grid: { left: 44, right: 16, top: 12, bottom: 28 },
  xAxis: {
    type: 'value',
    min: 0,
    max: growthXMax.value,
    axisLabel: { color: axisColor.value, fontSize: 10, formatter: (v: number) => `${v}${t('duration.monthShort')}` },
    axisLine: { lineStyle: { color: axisLineColor.value } },
  },
  yAxis: {
    type: 'value',
    scale: true,
    axisLabel: { color: '#8c7b72', fontSize: 10, formatter: (v: number) => `${v}cm` },
    splitLine: { lineStyle: { color: splitLineColor.value } },
  },
  tooltip: growthTooltip('cm'),
  series: [
    {
      name: 'P97',
      type: 'line',
      data: whoSeries('length', 'p97'),
      symbol: 'none',
      lineStyle: { width: 1, color: '#c4b6a6', type: 'dashed' },
      itemStyle: { color: '#c4b6a6' },
    },
    {
      name: 'P50',
      type: 'line',
      data: whoSeries('length', 'p50'),
      symbol: 'none',
      lineStyle: { width: 1, color: '#a49482', type: 'dashed' },
      itemStyle: { color: '#a49482' },
    },
    {
      name: 'P3',
      type: 'line',
      data: whoSeries('length', 'p3'),
      symbol: 'none',
      lineStyle: { width: 1, color: '#c4b6a6', type: 'dashed' },
      itemStyle: { color: '#c4b6a6' },
    },
    {
      name: t('stats.babyHeight'),
      type: 'line',
      data: heightPoints.value.map((p) => [p.month, p.height]),
      smooth: true,
      symbol: 'circle',
      symbolSize: 7,
      lineStyle: { width: 2.5, color: CHART_COLORS.sleep },
      itemStyle: { color: CHART_COLORS.sleep },
    },
  ],
}))
</script>

<template>
  <div class="page stats-page">
    <PageHeader />

    <!-- 时间范围 -->
    <div class="range-select-row">
      <label class="range-select-label" for="range-select">{{ t('stats.rangeLabel') }}</label>
      <select id="range-select" v-model="rangeKey" class="form-input range-select">
        <option v-for="p in RANGE_PRESETS" :key="p.key" :value="p.key">{{ t(p.label) }}</option>
      </select>
    </div>

    <!-- 概览：与上一周期对比 / 区间汇总（tab 切换） -->
    <div class="card overview-card">
      <div class="overview-tabs" role="tablist">
        <button
          class="overview-tab"
          :class="{ active: overviewTab === 'compare' }"
          role="tab"
          :aria-selected="overviewTab === 'compare'"
          @click="overviewTab = 'compare'"
        >
          {{ t('stats.compareTitle') }}
        </button>
        <button
          class="overview-tab"
          :class="{ active: overviewTab === 'summary' }"
          role="tab"
          :aria-selected="overviewTab === 'summary'"
          @click="overviewTab = 'summary'"
        >
          {{ t('stats.summaryTitle', { range: rangeLabel }) }}
        </button>
      </div>

      <div v-if="overviewTab === 'compare'" class="overview-body">
        <span class="overview-sub">{{ t('stats.compareSub', { range: rangeLabel }) }}</span>
        <div class="compare-grid">
          <div v-for="c in comparisons" :key="c.key" class="compare-item">
            <p class="compare-label">{{ t(c.label) }}</p>
            <p class="compare-value">{{ formatComparisonValue(c, c.current) }}</p>
            <div class="compare-change-row">
              <span class="compare-change" :class="c.change === null ? 'none' : c.change >= 0 ? 'up' : 'down'">
                {{ c.change === null ? '—' : formatPercentChange(c.change) }}
              </span>
              <span class="compare-prev"
                >{{ formatComparisonValue(c, c.previous) }} → {{ formatComparisonValue(c, c.current) }}</span
              >
            </div>
          </div>
        </div>
      </div>

      <div v-else class="overview-body">
        <span class="overview-sub">{{ t('stats.summarySub', { n: summaryDays }) }}</span>
        <div class="summary-grid">
          <div v-for="s in summaryItems" :key="s.label" class="summary-item">
            <p class="summary-label">{{ s.label }}</p>
            <p class="summary-value">{{ s.value }}</p>
            <p class="summary-sub">{{ s.sub }}</p>
          </div>
        </div>
      </div>
    </div>

    <!-- 趋势图 -->
    <ChartCard
      :title="t('stats.charts.milkTitle')"
      :subtitle="`${rangeLabel} · ${t('stats.charts.milkSub')}`"
      :option="milkOption"
    />
    <ChartCard :title="t('stats.charts.sleepTitle')" :subtitle="rangeLabel" :option="sleepOption" />
    <ChartCard
      :title="t('stats.charts.diaperTitle')"
      :subtitle="`${rangeLabel} · ${t('stats.charts.diaperSub')}`"
      :option="diaperOption"
    />
    <ChartCard :title="t('stats.charts.pumpTitle')" :subtitle="rangeLabel" :option="pumpOption" />
    <ChartCard
      :title="t('stats.charts.temperatureTitle')"
      :subtitle="`${rangeLabel} · ${t('stats.charts.temperatureSub')}`"
      :option="temperatureOption"
    />

    <!-- 成长曲线 -->
    <p class="section-title">{{ t('stats.growthSection') }}</p>
    <template v-if="hasBirthDate">
      <ChartCard
        v-if="weightPoints.length > 0"
        :title="t('stats.growthTitle')"
        :subtitle="t('stats.growthSub', { name: activeBaby?.name ?? '' })"
        :option="weightOption"
      />
      <ChartCard
        v-else-if="hasGrowthData"
        :title="t('stats.growthTitle')"
        :subtitle="t('stats.growthEmpty')"
        :option="{
          grid: { top: 40 },
          xAxis: { type: 'value', axisLabel: { show: false } },
          yAxis: { type: 'value', axisLabel: { show: false } },
          series: [],
        }"
      />
      <ChartCard
        v-if="heightPoints.length > 0"
        :title="t('stats.heightTitle')"
        :subtitle="t('stats.growthSub', { name: activeBaby?.name ?? '' })"
        :option="heightOption"
      />
      <ChartCard
        v-else-if="hasGrowthData"
        :title="t('stats.heightTitle')"
        :subtitle="t('stats.heightEmpty')"
        :option="{
          grid: { top: 40 },
          xAxis: { type: 'value', axisLabel: { show: false } },
          yAxis: { type: 'value', axisLabel: { show: false } },
          series: [],
        }"
      />
      <div v-if="!hasGrowthData" class="card empty-inline">
        {{ t('stats.growthEmptyBoth') }}
      </div>
    </template>
    <div v-else class="card empty-inline">
      {{ t('stats.growthCta', { name: activeBaby?.name ?? t('common.baby') }) }}
    </div>

    <p class="note-text">{{ t('stats.noteText') }}</p>
  </div>
</template>

<style scoped>
.range-select-row {
  display: flex;
  align-items: center;
  gap: 12px;
  padding: 6px 4px 14px;
}

.range-select-label {
  font-size: 13px;
  font-weight: 600;
  color: var(--text-secondary);
  flex-shrink: 0;
}

.range-select {
  flex: 1;
  min-width: 0;
  border-radius: 12px;
  box-shadow: var(--shadow-xs);
}

.overview-card {
  margin-bottom: 12px;
  padding: 16px;
}

.overview-tabs {
  display: flex;
  gap: 4px;
  background: var(--surface-2);
  border-radius: 999px;
  padding: 4px;
  margin-bottom: 14px;
}

.overview-tab {
  flex: 1;
  min-width: 0; /* 允许收缩，避免长文本（如英文 tab）撑破容器 */
  min-height: 0; /* 覆盖全局 button min-height:44px */
  padding: 9px 12px;
  border-radius: 999px;
  font-size: 13px;
  font-weight: 600;
  color: var(--text-secondary);
  transition: all 0.18s ease;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}

.overview-tab.active {
  background: var(--surface);
  color: var(--primary-dark);
  box-shadow: 0 1px 4px rgba(0, 0, 0, 0.1);
}

.overview-sub {
  display: block;
  font-size: 12px;
  color: var(--text-muted);
  margin-bottom: 12px;
}

.summary-grid {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 10px;
}

@media (max-width: 400px) {
  .summary-grid {
    grid-template-columns: repeat(2, 1fr);
    gap: 8px;
  }
}

.summary-item {
  background: var(--surface-2);
  border: 1px solid var(--border);
  border-radius: 14px;
  padding: 11px 8px;
  text-align: center;
  transition: transform 0.12s ease;
}

.summary-item:active {
  transform: scale(0.97);
}

.summary-label {
  font-size: 11px;
  color: var(--text-secondary);
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}

.summary-value {
  font-size: 15px;
  font-weight: 700;
  color: var(--text);
  margin-top: 3px;
  font-variant-numeric: tabular-nums;
  overflow-wrap: anywhere;
  word-break: break-word;
}

.summary-sub {
  font-size: 10px;
  color: var(--text-muted);
  margin-top: 3px;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}

.compare-head {
  margin-bottom: 12px;
}

.compare-title {
  font-size: 15px;
  font-weight: 700;
  color: var(--text);
}

.compare-sub {
  font-size: 12px;
  color: var(--text-muted);
  margin-top: 2px;
  display: block;
}

.compare-grid {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 10px;
}

@media (max-width: 400px) {
  .compare-grid {
    grid-template-columns: repeat(2, 1fr);
    gap: 8px;
  }
}

.compare-item {
  background: var(--surface-2);
  border: 1px solid var(--border);
  border-radius: 14px;
  padding: 11px 8px;
  text-align: center;
  transition: transform 0.12s ease;
}

.compare-item:active {
  transform: scale(0.97);
}

.compare-label {
  font-size: 11px;
  color: var(--text-secondary);
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}

.compare-value {
  font-size: 15px;
  font-weight: 700;
  color: var(--text);
  margin-top: 3px;
  font-variant-numeric: tabular-nums;
  overflow-wrap: anywhere;
  word-break: break-word;
}

.compare-change-row {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 1px;
  margin-top: 4px;
}

.compare-change {
  font-size: 13px;
  font-weight: 700;
}

.compare-change.up {
  color: #d97a52;
}

.compare-change.down {
  color: #7fae6c;
}

.compare-change.none {
  color: var(--text-muted);
}

.compare-prev {
  font-size: 10px;
  color: var(--text-muted);
  font-variant-numeric: tabular-nums;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
  max-width: 100%;
}

@media (max-width: 400px) {
  .compare-item {
    padding: 8px 4px;
  }

  .compare-value {
    font-size: 13px;
  }

  .compare-prev {
    font-size: 9px;
  }
}

.note-text {
  font-size: 12px;
  color: var(--text-muted);
  margin: 12px 4px 4px;
  line-height: 1.6;
}

.section-title {
  font-size: 15px;
  font-weight: 700;
  color: var(--text);
  margin: 18px 2px 10px;
}

.empty-inline {
  text-align: center;
  padding: 28px 12px;
  color: var(--text-secondary);
  font-size: 13px;
  line-height: 1.6;
}
</style>
