// src/components/forms/DiaperForm.tsx
'use client'

import { useState } from 'react'
import { useTranslation } from 'react-i18next'
import type { DiaperType, DiaperColor, DiaperAmount } from '@/types'
import { DIAPER_TYPE_LIST, DIAPER_COLOR_LABELS, DIAPER_COLOR_DOTS, DIAPER_AMOUNT_LABELS } from '@/constants'
import { toDateTimeLocal, fromDateTimeLocal } from '@/utils/format'
import { db } from '@/db'
import { useBabies } from '@/stores/baby'
import FormNotes from '@/components/common/FormNotes'
import FormActions from '@/components/common/FormActions'
import s from './DiaperForm.module.css'

export interface DiaperFormProps {
  editing?: {
    id: number
    type: DiaperType
    time: number
    color?: DiaperColor
    amount?: DiaperAmount
    notes?: string
  }
  onSaved?: () => void
  onCancelled?: () => void
}

export default function DiaperForm({ editing, onSaved, onCancelled }: DiaperFormProps) {
  const { t } = useTranslation()
  const { activeBabyId } = useBabies()

  const [type, setType] = useState<DiaperType>(editing?.type ?? 'wet')
  const [color, setColor] = useState<DiaperColor | ''>(editing?.color ?? '')
  const [amount, setAmount] = useState<DiaperAmount | ''>(editing?.amount ?? '')
  const [time, setTime] = useState(() => toDateTimeLocal(editing?.time ?? Date.now()))
  const [notes, setNotes] = useState(editing?.notes ?? '')

  const colorEntries = Object.entries(DIAPER_COLOR_LABELS) as [DiaperColor, string][]
  const amountEntries = Object.entries(DIAPER_AMOUNT_LABELS) as [DiaperAmount, string][]

  async function submit() {
    const ts = fromDateTimeLocal(time) ?? Date.now()
    if (editing) {
      await db.diapers.update(editing.id, {
        type,
        time: ts,
        color: color || undefined,
        amount: amount || undefined,
        notes: notes || undefined,
        updatedAt: Date.now(),
      })
    } else {
      if (activeBabyId == null) throw new Error(t('errors.noBaby'))
      const now = Date.now()
      const id = await db.diapers.add({
        babyId: activeBabyId,
        type,
        time: ts,
        color: color || undefined,
        amount: amount || undefined,
        notes: notes || undefined,
        createdAt: now,
        updatedAt: now,
      })
      if (id == null) throw new Error(t('errors.addDiaperFail'))
    }
    onSaved?.()
  }

  return (
    <div className="diaper-form">
      <p className="form-label">{t('diaper.typeLabel')}</p>
      <div className={s['type-grid']}>
        {DIAPER_TYPE_LIST.map((opt) => (
          <button
            key={opt.value}
            type="button"
            className={type === opt.value ? `${s['type-btn']} ${s.selected}` : s['type-btn']}
            style={
              type === opt.value ? { background: opt.color + '22', borderColor: opt.color, color: opt.color } : undefined
            }
            onClick={() => setType(opt.value)}
          >
            <span className={s['type-icon']}>{opt.icon}</span>
            <span className={s['type-label']}>{t(opt.label)}</span>
          </button>
        ))}
      </div>

      <div className="form-field">
        <label className="form-label">{t('diaper.colorLabel')}</label>
        <div className={s['color-row']}>
          {colorEntries.map(([key, label]) => (
            <button
              key={key}
              type="button"
              className={color === key ? `${s['color-dot-btn']} ${s.selected}` : s['color-dot-btn']}
              onClick={() => setColor(color === key ? '' : key)}
            >
              <span className={s['color-dot']} style={{ background: DIAPER_COLOR_DOTS[key] }} />
              <span className={s['color-label']}>{t(label)}</span>
            </button>
          ))}
        </div>
      </div>

      <div className="form-field">
        <label className="form-label">{t('diaper.amountLabel')}</label>
        <div className={s['amount-row']}>
          {amountEntries.map(([key, label]) => (
            <button
              key={key}
              type="button"
              className={amount === key ? `${s['amount-btn']} ${s.selected}` : s['amount-btn']}
              onClick={() => setAmount(amount === key ? '' : key)}
            >
              {t(label)}
            </button>
          ))}
        </div>
      </div>

      <div className="form-field">
        <label className="form-label">{t('diaper.timeLabel')}</label>
        <input
          value={time}
          type="datetime-local"
          placeholder={t('common.selectDateTime')}
          className="form-input"
          onChange={(e) => setTime(e.target.value)}
        />
      </div>

      <FormNotes value={notes} label={t('diaper.notesLabel')} placeholder={t('common.optional')} onChange={setNotes} />

      <FormActions editing={editing != null} onCancelled={onCancelled} onSave={submit} />
    </div>
  )
}

// src/components/forms/DiaperForm.vue
<script setup lang="ts">
import { ref } from 'vue'
import { useI18n } from 'vue-i18n'
import type { DiaperType, DiaperColor, DiaperAmount } from '@/types'
import { DIAPER_TYPE_LIST, DIAPER_COLOR_LABELS, DIAPER_COLOR_DOTS, DIAPER_AMOUNT_LABELS } from '@/constants'
import { toDateTimeLocal, fromDateTimeLocal } from '@/utils/format'
import { useDiaperStore } from '@/stores/diaper'
import FormNotes from '@/components/common/FormNotes.vue'
import FormActions from '@/components/common/FormActions.vue'

const { t } = useI18n()

const props = defineProps<{
  editing?: { id: number; type: DiaperType; time: number; color?: DiaperColor; amount?: DiaperAmount; notes?: string }
}>()
const emit = defineEmits<{ saved: []; cancelled: [] }>()

const diaperStore = useDiaperStore()

const type = ref<DiaperType>(props.editing?.type ?? 'wet')
const color = ref<DiaperColor | ''>(props.editing?.color ?? '')
const amount = ref<DiaperAmount | ''>(props.editing?.amount ?? '')
const time = ref(toDateTimeLocal(props.editing?.time ?? Date.now()))
const notes = ref(props.editing?.notes ?? '')

async function submit() {
  const ts = fromDateTimeLocal(time.value) ?? Date.now()
  if (props.editing) {
    await diaperStore.update(props.editing.id, {
      type: type.value,
      time: ts,
      color: color.value || undefined,
      amount: amount.value || undefined,
      notes: notes.value || undefined,
    })
  } else {
    await diaperStore.add({
      type: type.value,
      time: ts,
      color: color.value || undefined,
      amount: amount.value || undefined,
      notes: notes.value || undefined,
    })
  }
  emit('saved')
}
</script>

<template>
  <div class="diaper-form">
    <p class="form-label">{{ t('diaper.typeLabel') }}</p>
    <div class="type-grid">
      <button
        v-for="opt in DIAPER_TYPE_LIST"
        :key="opt.value"
        type="button"
        class="type-btn"
        :class="{ selected: type === opt.value }"
        :style="
          type === opt.value ? { background: opt.color + '22', borderColor: opt.color, color: opt.color } : undefined
        "
        @click="type = opt.value"
      >
        <span class="type-icon">{{ opt.icon }}</span>
        <span class="type-label">{{ t(opt.label) }}</span>
      </button>
    </div>

    <div class="form-field">
      <label class="form-label">{{ t('diaper.colorLabel') }}</label>
      <div class="color-row">
        <button
          v-for="(label, key) in DIAPER_COLOR_LABELS"
          :key="key"
          type="button"
          class="color-dot-btn"
          :class="{ selected: color === key }"
          @click="color = color === key ? '' : key"
        >
          <span class="color-dot" :style="{ background: DIAPER_COLOR_DOTS[key] }"></span>
          <span class="color-label">{{ t(label) }}</span>
        </button>
      </div>
    </div>

    <div class="form-field">
      <label class="form-label">{{ t('diaper.amountLabel') }}</label>
      <div class="amount-row">
        <button
          v-for="(label, key) in DIAPER_AMOUNT_LABELS"
          :key="key"
          type="button"
          class="amount-btn"
          :class="{ selected: amount === key }"
          @click="amount = amount === key ? '' : key"
        >
          {{ t(label) }}
        </button>
      </div>
    </div>

    <div class="form-field">
      <label class="form-label">{{ t('diaper.timeLabel') }}</label>
      <input v-model="time" type="datetime-local" :placeholder="t('common.selectDateTime')" class="form-input" />
    </div>

    <FormNotes v-model="notes" :label="t('diaper.notesLabel')" :placeholder="t('common.optional')" />

    <FormActions :editing="props.editing != null" @cancelled="emit('cancelled')" @save="submit" />
  </div>
</template>

<style scoped>
.type-grid {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 10px;
  margin-bottom: 16px;
}

.type-btn {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 4px;
  padding: 12px 6px;
  border-radius: var(--radius-sm);
  border: 1px solid var(--glass-border);
  background: var(--surface);
  transition: all 0.3s var(--spring);
}

.type-btn.selected {
  border-width: 1.5px;
}

.type-icon {
  font-size: 20px;
}

.type-label {
  font-size: 12px;
  font-weight: 600;
  color: var(--text-secondary);
  white-space: nowrap;
}

.color-row {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
}

.color-dot-btn {
  display: flex;
  align-items: center;
  gap: 5px;
  padding: 6px 10px;
  border-radius: 999px;
  border: 1px solid var(--glass-border);
  background: var(--surface);
  font-size: 12px;
  color: var(--text-secondary);
  transition: all 0.3s var(--spring);
}

.color-dot-btn.selected {
  border-color: var(--primary);
  background: var(--primary-soft);
  color: var(--primary-dark);
}

.color-dot {
  width: 14px;
  height: 14px;
  border-radius: 50%;
}

.amount-row {
  display: flex;
  gap: 8px;
}

.amount-btn {
  flex: 1;
  padding: 8px;
  border-radius: var(--radius-sm);
  border: 1px solid var(--glass-border);
  background: var(--surface);
  font-size: 13px;
  color: var(--text-secondary);
  transition: all 0.3s var(--spring);
}

.amount-btn.selected {
  border-color: var(--primary);
  background: var(--primary-soft);
  color: var(--primary-dark);
  font-weight: 600;
}
</style>
