// src/components/forms/FeedingForm.tsx
'use client'

import { useEffect, useState } from 'react'
import { useTranslation } from 'react-i18next'
import type { FeedType, BreastSide } from '@/types'
import { FEED_TYPE_LIST, BREAST_SIDE_LIST } from '@/constants'
import { toDateTimeLocal, fromDateTimeLocal, formatDuration } from '@/utils/format'
import { db } from '@/db'
import { useBabies } from '@/stores/baby'
import { toast } from '@/stores/toast'
import { useActiveTimer } from '@/hooks/useActiveTimer'
import FormNotes from '@/components/common/FormNotes'
import FormActions from '@/components/common/FormActions'
import s from './FeedingForm.module.css'

export interface FeedingFormProps {
  editing?: {
    id: number
    type: FeedType
    side?: BreastSide
    startTime: number
    endTime?: number
    duration?: number
    amount?: number
    notes?: string
  }
  onSaved?: () => void
  onCancelled?: () => void
  onStartRecord?: () => void
}

export default function FeedingForm({ editing, onSaved, onCancelled, onStartRecord }: FeedingFormProps) {
  const { t } = useTranslation()
  const { activeBabyId } = useBabies()
  const { getByKind, start: startTimer, reset: resetTimer } = useActiveTimer()

  const [type, setType] = useState<FeedType>(editing?.type ?? 'breast')
  const [side, setSide] = useState<BreastSide>(editing?.side ?? 'left')
  const [amount, setAmount] = useState(editing?.amount != null ? String(editing.amount) : '')
  const [notes, setNotes] = useState(editing?.notes ?? '')
  const [startTime, setStartTime] = useState(() => toDateTimeLocal(editing?.startTime ?? Date.now()))
  const [endTime, setEndTime] = useState(editing?.endTime ? toDateTimeLocal(editing.endTime) : '')

  const isBreast = type === 'breast'
  const activeEntry = getByKind('feeding')
  const isRecording = !!activeEntry
  const isEditing = !!editing && !isRecording

  const durStart = fromDateTimeLocal(startTime)
  const durEnd = endTime ? fromDateTimeLocal(endTime) : undefined
  const durationText = durStart && durEnd && durEnd > durStart ? formatDuration(durEnd - durStart) : null

  const submitLabel = isEditing ? t('common.saveEdit') : isRecording ? t('feed.endRecord') : t('feed.startRecord')

  useEffect(() => {
    const entry = getByKind('feeding')
    if (!entry) return
    let stale = false
    void db.feedings.get(entry.recordId).then((record) => {
      if (!record || stale) return
      setType(record.type)
      setSide(record.side ?? 'left')
      setAmount(record.amount != null ? String(record.amount) : '')
      setNotes(record.notes ?? '')
      setStartTime(toDateTimeLocal(record.startTime))
      setEndTime('')
    })
    return () => {
      stale = true
    }
  }, [getByKind])

  async function submit() {
    try {
      const startTs = fromDateTimeLocal(startTime) ?? Date.now()
      const end = endTime ? fromDateTimeLocal(endTime) : undefined

      if (isRecording && activeEntry) {
        const endTs = end ?? Date.now()
        await db.feedings.update(activeEntry.recordId, {
          endTime: endTs,
          duration: endTs > startTs ? endTs - startTs : undefined,
          updatedAt: Date.now(),
        })
        resetTimer(activeEntry.id)
        onSaved?.()
        return
      }

      if (isEditing && editing) {
        await db.feedings.update(editing.id, {
          type,
          side: isBreast ? side : undefined,
          startTime: startTs,
          endTime: end,
          duration: end && end > startTs ? end - startTs : undefined,
          amount: isBreast ? undefined : amount ? Number(amount) : undefined,
          notes: notes || undefined,
          updatedAt: Date.now(),
        })
        onSaved?.()
        return
      }

      if (isBreast) {
        if (activeBabyId == null) throw new Error(t('errors.noBaby'))
        const now = Date.now()
        const id = await db.feedings.add({
          babyId: activeBabyId,
          type,
          side,
          startTime: startTs,
          endTime: undefined,
          duration: undefined,
          amount: undefined,
          notes: notes || undefined,
          createdAt: now,
          updatedAt: now,
        })
        if (id == null) throw new Error(t('errors.addFeedFail'))
        startTimer('feeding', id, startTs)
      } else {
        const amt = Number(amount)
        if (!amount || isNaN(amt) || amt <= 0) {
          alert(t('feed.invalidAmount'))
          return
        }
        if (activeBabyId == null) throw new Error(t('errors.noBaby'))
        const now = Date.now()
        const id = await db.feedings.add({
          babyId: activeBabyId,
          type,
          side: undefined,
          startTime: startTs,
          endTime: undefined,
          duration: undefined,
          amount: amt,
          notes: notes || undefined,
          createdAt: now,
          updatedAt: now,
        })
        if (id == null) throw new Error(t('errors.addFeedFail'))
        startTimer('feeding', id, startTs)
      }
      onStartRecord?.()
    } catch {
      toast(t('errors.generic'))
    }
  }

  return (
    <div className="feeding-form">
      <p className="form-label">{t('feed.typeLabel')}</p>
      <div className={s['type-grid']}>
        {FEED_TYPE_LIST.map((opt) => (
          <button
            key={opt.value}
            type="button"
            className={type === opt.value ? `${s['type-btn']} ${s.selected}` : s['type-btn']}
            style={
              type === opt.value ? { background: opt.color + '22', borderColor: opt.color, color: opt.color } : undefined
            }
            onClick={() => setType(opt.value)}
          >
            <span className={s['type-icon']}>{opt.icon}</span>
            <span className={s['type-label']}>{t(opt.label)}</span>
          </button>
        ))}
      </div>

      {isBreast && (
        <div className={s['side-row']}>
          {BREAST_SIDE_LIST.map((sd) => (
            <button
              key={sd.value}
              type="button"
              className={side === sd.value ? `${s['side-btn']} ${s.selected}` : s['side-btn']}
              onClick={() => setSide(sd.value)}
            >
              <span>{sd.icon}</span>
              <span>{t(sd.label)}</span>
            </button>
          ))}
        </div>
      )}

      {!isBreast && (
        <div className="form-field">
          <label className="form-label">{t('feed.amountLabel')}</label>
          <input
            value={amount}
            type="number"
            min={0}
            step={5}
            placeholder={t('feed.amountPlaceholder')}
            className="form-input"
            inputMode="decimal"
            onChange={(e) => setAmount(e.target.value)}
          />
        </div>
      )}

      <div className={s['time-row']}>
        <div className="form-field">
          <label className="form-label">{t('feed.startLabel')}</label>
          <input
            value={startTime}
            type="datetime-local"
            placeholder={t('common.selectDateTime')}
            className="form-input"
            disabled={isRecording}
            onChange={(e) => setStartTime(e.target.value)}
          />
        </div>
        <div className="form-field">
          <label className="form-label">{t('feed.endLabel')}</label>
          <input
            value={endTime}
            type="datetime-local"
            placeholder={t('common.selectDateTime')}
            className="form-input"
            onChange={(e) => setEndTime(e.target.value)}
          />
        </div>
      </div>

      {durationText && <p className={s['duration-hint']}>{durationText}</p>}

      <FormNotes value={notes} label={t('feed.notesLabel')} placeholder={t('common.optional')} onChange={setNotes} />

      <FormActions editing={isEditing} submitLabel={submitLabel} onCancelled={onCancelled} onSave={submit} />
    </div>
  )
}

// src/components/forms/FeedingForm.vue
<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { useI18n } from 'vue-i18n'
import type { FeedType, BreastSide } from '@/types'
import { FEED_TYPE_LIST, BREAST_SIDE_LIST } from '@/constants'
import { toDateTimeLocal, fromDateTimeLocal, formatDuration } from '@/utils/format'
import { useFeedingStore } from '@/stores/feeding'
import { useActiveTimer } from '@/composables/useActiveTimer'
import { showToast } from '@/composables/useToast'
import FormNotes from '@/components/common/FormNotes.vue'
import FormActions from '@/components/common/FormActions.vue'

const { t } = useI18n()

const props = defineProps<{
  editing?: {
    id: number
    type: FeedType
    side?: BreastSide
    startTime: number
    endTime?: number
    duration?: number
    amount?: number
    notes?: string
  }
}>()
const emit = defineEmits<{ saved: []; cancelled: []; startRecord: [] }>()

const feedingStore = useFeedingStore()
const activeTimer = useActiveTimer()

const type = ref<FeedType>(props.editing?.type ?? 'breast')
const side = ref<BreastSide>(props.editing?.side ?? 'left')
const isBreast = computed(() => type.value === 'breast')
const amount = ref<string>(props.editing?.amount != null ? String(props.editing.amount) : '')
const notes = ref(props.editing?.notes ?? '')
const startTime = ref(toDateTimeLocal(props.editing?.startTime ?? Date.now()))
const endTime = ref(props.editing?.endTime ? toDateTimeLocal(props.editing.endTime) : '')

const activeEntry = computed(() => activeTimer.getByKind('feeding'))
const isRecording = computed(() => !!activeEntry.value)
const isEditing = computed(() => !!props.editing && !isRecording.value)

const durationText = computed(() => {
  const start = fromDateTimeLocal(startTime.value)
  const end = endTime.value ? fromDateTimeLocal(endTime.value) : undefined
  if (start && end && end > start) return formatDuration(end - start)
  return null
})

const submitLabel = computed(() => {
  if (isEditing.value) return t('common.saveEdit')
  if (isRecording.value) return t('feed.endRecord')
  return t('feed.startRecord')
})

onMounted(() => {
  if (activeEntry.value) {
    const record = feedingStore.feedings.find((f) => f.id === activeEntry.value!.recordId)
    if (record) {
      type.value = record.type
      side.value = record.side ?? 'left'
      amount.value = record.amount != null ? String(record.amount) : ''
      notes.value = record.notes ?? ''
      startTime.value = toDateTimeLocal(record.startTime)
      endTime.value = ''
    }
  }
})

async function submit() {
  try {
    const start = fromDateTimeLocal(startTime.value) ?? Date.now()
    const end = endTime.value ? fromDateTimeLocal(endTime.value) : undefined

    if (isRecording.value && activeEntry.value) {
      const endTs = end ?? Date.now()
      await feedingStore.update(activeEntry.value.recordId, {
        endTime: endTs,
        duration: endTs > start ? endTs - start : undefined,
      })
      activeTimer.reset(activeEntry.value.id)
      emit('saved')
      return
    }

    if (isEditing.value && props.editing) {
      await feedingStore.update(props.editing.id, {
        type: type.value,
        side: isBreast.value ? side.value : undefined,
        startTime: start,
        endTime: end,
        duration: end && end > start ? end - start : undefined,
        amount: isBreast.value ? undefined : amount.value ? Number(amount.value) : undefined,
        notes: notes.value || undefined,
      })
      emit('saved')
      return
    }

    if (isBreast.value) {
      const id = await feedingStore.add({ type: type.value, side: side.value, startTime: start, notes: notes.value || undefined })
      activeTimer.start('feeding', id, start)
    } else {
      const amt = Number(amount.value)
      if (!amount.value || isNaN(amt) || amt <= 0) {
        alert(t('feed.invalidAmount'))
        return
      }
      const id = await feedingStore.add({ type: type.value, startTime: start, amount: amt, notes: notes.value || undefined })
      activeTimer.start('feeding', id, start)
    }
    emit('startRecord')
  } catch {
    showToast(t('errors.generic'))
  }
}
</script>

<template>
  <div class="feeding-form">
    <p class="form-label">{{ t('feed.typeLabel') }}</p>
    <div class="type-grid">
      <button
        v-for="opt in FEED_TYPE_LIST"
        :key="opt.value"
        type="button"
        class="type-btn"
        :class="{ selected: type === opt.value }"
        :style="
          type === opt.value ? { background: opt.color + '22', borderColor: opt.color, color: opt.color } : undefined
        "
        @click="type = opt.value"
      >
        <span class="type-icon">{{ opt.icon }}</span>
        <span class="type-label">{{ t(opt.label) }}</span>
      </button>
    </div>

    <div v-if="isBreast" class="side-row">
      <button
        v-for="s in BREAST_SIDE_LIST"
        :key="s.value"
        type="button"
        class="side-btn"
        :class="{ selected: side === s.value }"
        @click="side = s.value"
      >
        <span>{{ s.icon }}</span>
        <span>{{ t(s.label) }}</span>
      </button>
    </div>

    <div v-if="!isBreast" class="form-field">
      <label class="form-label">{{ t('feed.amountLabel') }}</label>
      <input
        v-model="amount"
        type="number"
        min="0"
        step="5"
        :placeholder="t('feed.amountPlaceholder')"
        class="form-input"
        inputmode="decimal"
      />
    </div>

    <div class="time-row">
      <div class="form-field">
        <label class="form-label">{{ t('feed.startLabel') }}</label>
        <input
          v-model="startTime"
          type="datetime-local"
          :placeholder="t('common.selectDateTime')"
          class="form-input"
          :disabled="isRecording"
        />
      </div>
      <div class="form-field">
        <label class="form-label">{{ t('feed.endLabel') }}</label>
        <input v-model="endTime" type="datetime-local" :placeholder="t('common.selectDateTime')" class="form-input" />
      </div>
    </div>

    <p v-if="durationText" class="duration-hint">{{ durationText }}</p>

    <FormNotes v-model="notes" :label="t('feed.notesLabel')" :placeholder="t('common.optional')" />

    <FormActions
      :editing="isEditing"
      :submit-label="submitLabel"
      @cancelled="emit('cancelled')"
      @save="submit"
    />
  </div>
</template>

<style scoped>
.type-grid {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 10px;
  margin-bottom: 16px;
}

.type-btn {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 4px;
  padding: 12px 6px;
  border-radius: var(--radius-sm);
  border: 1px solid var(--glass-border);
  background: var(--surface);
  transition: all 0.3s var(--spring);
}

.type-btn.selected {
  border-width: 1.5px;
}

.type-icon {
  font-size: 20px;
}

.type-label {
  font-size: 12px;
  font-weight: 600;
  color: var(--text-secondary);
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.side-row {
  display: flex;
  gap: 10px;
  margin-bottom: 16px;
}

.side-btn {
  flex: 1;
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 6px;
  padding: 10px 8px;
  border-radius: var(--radius-sm);
  border: 1px solid var(--glass-border);
  background: var(--surface);
  font-size: 13px;
  font-weight: 600;
  color: var(--text-secondary);
  cursor: pointer;
  transition: all 0.3s var(--spring);
}

.side-btn.selected {
  border-color: var(--primary);
  color: var(--primary);
  background: rgba(232, 144, 108, 0.08);
}

.side-btn:active {
  transform: scale(0.97);
}

.duration-hint {
  font-size: 13px;
  color: var(--text-secondary);
  text-align: center;
  margin-bottom: 12px;
}

.time-row {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
  gap: 10px;
}

@media (max-width: 480px) {
  .time-row {
    grid-template-columns: 1fr;
  }
}

@media (max-width: 375px) {
  .type-grid { gap: 8px; }
  .type-btn { padding: 10px 4px; }
  .type-icon { font-size: 18px; }
  .type-label { font-size: 11px; }
  .side-btn { padding: 8px 6px; font-size: 12px; }
}
</style>
