// src/components/forms/GrowthForm.tsx
'use client'

import { useState } from 'react'
import { useTranslation } from 'react-i18next'
import { toDateTimeLocal, fromDateTimeLocal } from '@/utils/format'
import { db } from '@/db'
import { useBabies } from '@/stores/baby'
import FormNotes from '@/components/common/FormNotes'
import FormActions from '@/components/common/FormActions'

export interface GrowthFormProps {
  editing?: {
    id: number
    date: number
    weight?: number
    height?: number
    headCircumference?: number
    notes?: string
  }
  onSaved?: () => void
  onCancelled?: () => void
}

export default function GrowthForm({ editing, onSaved, onCancelled }: GrowthFormProps) {
  const { t } = useTranslation()
  const { activeBabyId } = useBabies()

  const [date, setDate] = useState(() => toDateTimeLocal(editing?.date ?? Date.now()).slice(0, 10))
  const [weight, setWeight] = useState(editing?.weight != null ? String(editing.weight) : '')
  const [height, setHeight] = useState(editing?.height != null ? String(editing.height) : '')
  const [headCircumference, setHeadCircumference] = useState(
    editing?.headCircumference != null ? String(editing.headCircumference) : '',
  )
  const [notes, setNotes] = useState(editing?.notes ?? '')

  async function submit() {
    const d = fromDateTimeLocal(date + 'T00:00:00')
    if (d == null || isNaN(d)) {
      alert(t('growth.invalidDate'))
      return
    }
    const w = weight ? Number(weight) : undefined
    const h = height ? Number(height) : undefined
    const hc = headCircumference ? Number(headCircumference) : undefined
    if (w !== undefined && (isNaN(w) || w <= 0)) {
      alert(t('growth.invalidWeight'))
      return
    }
    if (h !== undefined && (isNaN(h) || h <= 0)) {
      alert(t('growth.invalidHeight'))
      return
    }
    if (hc !== undefined && (isNaN(hc) || hc <= 0)) {
      alert(t('growth.invalidHead'))
      return
    }
    if (w === undefined && h === undefined && hc === undefined) {
      alert(t('growth.invalidEmpty'))
      return
    }

    if (editing) {
      await db.growths.update(editing.id, {
        date: d,
        weight: w,
        height: h,
        headCircumference: hc,
        notes: notes || undefined,
        updatedAt: Date.now(),
      })
    } else {
      if (activeBabyId == null) throw new Error(t('errors.noBaby'))
      const now = Date.now()
      const id = await db.growths.add({
        babyId: activeBabyId,
        date: d,
        weight: w,
        height: h,
        headCircumference: hc,
        notes: notes || undefined,
        createdAt: now,
        updatedAt: now,
      })
      if (id == null) throw new Error(t('errors.addGrowthFail'))
    }
    onSaved?.()
  }

  return (
    <div className="growth-form">
      <div className="form-field">
        <label className="form-label">{t('growth.dateLabel')}</label>
        <input
          value={date}
          type="date"
          placeholder={t('common.selectDate')}
          className="form-input"
          onChange={(e) => setDate(e.target.value)}
        />
      </div>

      <div className="form-field">
        <label className="form-label">{t('growth.weightLabel')}</label>
        <input
          value={weight}
          type="number"
          min={0}
          step={0.1}
          placeholder={t('growth.weightPlaceholder')}
          className="form-input"
          inputMode="decimal"
          onChange={(e) => setWeight(e.target.value)}
        />
      </div>

      <div className="form-field">
        <label className="form-label">{t('growth.heightLabel')}</label>
        <input
          value={height}
          type="number"
          min={0}
          step={0.5}
          placeholder={t('growth.heightPlaceholder')}
          className="form-input"
          inputMode="decimal"
          onChange={(e) => setHeight(e.target.value)}
        />
      </div>

      <div className="form-field">
        <label className="form-label">{t('growth.headLabel')}</label>
        <input
          value={headCircumference}
          type="number"
          min={0}
          step={0.1}
          placeholder={t('growth.headPlaceholder')}
          className="form-input"
          inputMode="decimal"
          onChange={(e) => setHeadCircumference(e.target.value)}
        />
      </div>

      <FormNotes value={notes} label={t('growth.notesLabel')} placeholder={t('common.optional')} onChange={setNotes} />

      <FormActions editing={editing != null} onCancelled={onCancelled} onSave={submit} />
    </div>
  )
}

// src/components/forms/GrowthForm.vue
<script setup lang="ts">
import { ref } from 'vue'
import { useI18n } from 'vue-i18n'
import { toDateTimeLocal, fromDateTimeLocal } from '@/utils/format'
import { useGrowthStore } from '@/stores/growth'
import FormNotes from '@/components/common/FormNotes.vue'
import FormActions from '@/components/common/FormActions.vue'

const { t } = useI18n()

const props = defineProps<{
  editing?: {
    id: number
    date: number
    weight?: number
    height?: number
    headCircumference?: number
    notes?: string
  }
}>()
const emit = defineEmits<{ saved: []; cancelled: [] }>()

const growthStore = useGrowthStore()

const date = ref(toDateTimeLocal(props.editing?.date ?? Date.now()).slice(0, 10))
const weight = ref<string>(props.editing?.weight != null ? String(props.editing.weight) : '')
const height = ref<string>(props.editing?.height != null ? String(props.editing.height) : '')
const headCircumference = ref<string>(
  props.editing?.headCircumference != null ? String(props.editing.headCircumference) : '',
)
const notes = ref(props.editing?.notes ?? '')

async function submit() {
  const d = fromDateTimeLocal(date.value + 'T00:00:00')
  if (d == null || isNaN(d)) {
    alert(t('growth.invalidDate'))
    return
  }
  const w = weight.value ? Number(weight.value) : undefined
  const h = height.value ? Number(height.value) : undefined
  const hc = headCircumference.value ? Number(headCircumference.value) : undefined
  if (w !== undefined && (isNaN(w) || w <= 0)) {
    alert(t('growth.invalidWeight'))
    return
  }
  if (h !== undefined && (isNaN(h) || h <= 0)) {
    alert(t('growth.invalidHeight'))
    return
  }
  if (hc !== undefined && (isNaN(hc) || hc <= 0)) {
    alert(t('growth.invalidHead'))
    return
  }
  if (w === undefined && h === undefined && hc === undefined) {
    alert(t('growth.invalidEmpty'))
    return
  }

  if (props.editing) {
    await growthStore.update(props.editing.id, {
      date: d,
      weight: w,
      height: h,
      headCircumference: hc,
      notes: notes.value || undefined,
    })
  } else {
    await growthStore.add({ date: d, weight: w, height: h, headCircumference: hc, notes: notes.value || undefined })
  }
  emit('saved')
}
</script>

<template>
  <div class="growth-form">
    <div class="form-field">
      <label class="form-label">{{ t('growth.dateLabel') }}</label>
      <input v-model="date" type="date" :placeholder="t('common.selectDate')" class="form-input" />
    </div>

    <div class="form-field">
      <label class="form-label">{{ t('growth.weightLabel') }}</label>
      <input
        v-model="weight"
        type="number"
        min="0"
        step="0.1"
        :placeholder="t('growth.weightPlaceholder')"
        class="form-input"
        inputmode="decimal"
      />
    </div>

    <div class="form-field">
      <label class="form-label">{{ t('growth.heightLabel') }}</label>
      <input
        v-model="height"
        type="number"
        min="0"
        step="0.5"
        :placeholder="t('growth.heightPlaceholder')"
        class="form-input"
        inputmode="decimal"
      />
    </div>

    <div class="form-field">
      <label class="form-label">{{ t('growth.headLabel') }}</label>
      <input
        v-model="headCircumference"
        type="number"
        min="0"
        step="0.1"
        :placeholder="t('growth.headPlaceholder')"
        class="form-input"
        inputmode="decimal"
      />
    </div>

    <FormNotes v-model="notes" :label="t('growth.notesLabel')" :placeholder="t('common.optional')" />

    <FormActions :editing="props.editing != null" @cancelled="emit('cancelled')" @save="submit" />
  </div>
</template>
