// src/components/forms/SleepForm.vue
﻿<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { useI18n } from 'vue-i18n'
import type { SleepType } from '@/types'
import { SLEEP_TYPE_LABELS } from '@/constants'
import { toDateTimeLocal, fromDateTimeLocal, formatDuration } from '@/utils/format'
import { useSleepStore } from '@/stores/sleep'
import { useActiveTimer } from '@/composables/useActiveTimer'
import { showToast } from '@/composables/useToast'
import FormNotes from '@/components/common/FormNotes.vue'
import FormActions from '@/components/common/FormActions.vue'

const { t } = useI18n()

const props = defineProps<{
  editing?: { id: number; type: SleepType; startTime: number; endTime: number; notes?: string }
}>()
const emit = defineEmits<{ saved: []; cancelled: []; startRecord: [] }>()

const sleepStore = useSleepStore()
const activeTimer = useActiveTimer()

const type = ref<SleepType>(props.editing?.type ?? 'nap')
const notes = ref(props.editing?.notes ?? '')
const startTime = ref(toDateTimeLocal(props.editing?.startTime ?? Date.now()))
const endTime = ref(props.editing?.endTime ? toDateTimeLocal(props.editing.endTime) : '')

const activeEntry = computed(() => activeTimer.getByKind('sleep'))
const isRecording = computed(() => !!activeEntry.value)
const isEditing = computed(() => !!props.editing && !isRecording.value)

const durationText = computed(() => {
  const start = fromDateTimeLocal(startTime.value)
  const end = endTime.value ? fromDateTimeLocal(endTime.value) : undefined
  if (start && end && end > start) return formatDuration(end - start)
  return null
})

const submitLabel = computed(() => {
  if (isEditing.value) return t('common.saveEdit')
  if (isRecording.value) return t('sleep.endRecord')
  return t('sleep.startRecord')
})

onMounted(() => {
  if (activeEntry.value) {
    const record = sleepStore.sleeps.find((s) => s.id === activeEntry.value!.recordId)
    if (record) {
      type.value = record.type
      notes.value = record.notes ?? ''
      startTime.value = toDateTimeLocal(record.startTime)
      endTime.value = ''
    }
  }
})

async function submit() {
  try {
    const start = fromDateTimeLocal(startTime.value) ?? Date.now()
    const end = endTime.value ? fromDateTimeLocal(endTime.value) : undefined

    if (isRecording.value && activeEntry.value) {
      const endTs = end ?? Date.now()
      if (endTs <= start) {
        alert(t('sleep.invalidOrder'))
        return
      }
      await sleepStore.update(activeEntry.value.recordId, {
        endTime: endTs,
        duration: endTs - start,
      })
      activeTimer.reset(activeEntry.value.id)
      emit('saved')
      return
    }

    if (isEditing.value && props.editing) {
      if (!end) {
        alert(t('sleep.invalidRange'))
        return
      }
      if (end <= start) {
        alert(t('sleep.invalidOrder'))
        return
      }
      await sleepStore.update(props.editing.id, {
        type: type.value,
        startTime: start,
        endTime: end,
        notes: notes.value || undefined,
      })
      emit('saved')
      return
    }

    const id = await sleepStore.add({ type: type.value, startTime: start, notes: notes.value || undefined })
    activeTimer.start('sleep', id, start)
    emit('startRecord')
  } catch {
    showToast(t('errors.generic'))
  }
}
</script>

<template>
  <div class="sleep-form">
    <p class="form-label">{{ t('sleep.typeLabel') }}</p>
    <div class="type-row">
      <button
        v-for="(label, key) in SLEEP_TYPE_LABELS"
        :key="key"
        type="button"
        class="type-btn"
        :class="{ selected: type === key }"
        @click="type = key"
      >
        <span class="type-icon">{{ key === 'night' ? '🌙' : '😴' }}</span>
        <span class="type-label">{{ t(label) }}</span>
      </button>
    </div>

    <div class="time-row">
      <div class="form-field">
        <label class="form-label">{{ t('sleep.startLabel') }}</label>
        <input
          v-model="startTime"
          type="datetime-local"
          :placeholder="t('common.selectDateTime')"
          class="form-input"
          :disabled="isRecording"
        />
      </div>
      <div class="form-field">
        <label class="form-label">{{ t('sleep.endLabel') }}</label>
        <input v-model="endTime" type="datetime-local" :placeholder="t('common.selectDateTime')" class="form-input" />
      </div>
    </div>

    <p v-if="durationText" class="duration-hint">{{ durationText }}</p>

    <FormNotes v-model="notes" :label="t('sleep.notesLabel')" :placeholder="t('common.optional')" />

    <FormActions
      :editing="isEditing"
      :submit-label="submitLabel"
      @cancelled="emit('cancelled')"
      @save="submit"
    />
  </div>
</template>

<style scoped>
.type-row {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 10px;
  margin-bottom: 16px;
}

.type-btn {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 4px;
  padding: 12px 6px;
  border-radius: var(--radius-sm);
  border: 1px solid var(--glass-border);
  background: var(--surface);
  transition: all 0.3s var(--spring);
}

.type-btn.selected {
  border-color: var(--primary);
  background: var(--primary-soft);
  color: var(--primary-dark);
}

.type-icon { font-size: 20px; }

.type-label {
  font-size: 12px;
  font-weight: 600;
  color: var(--text-secondary);
}

.duration-hint {
  font-size: 13px;
  color: var(--text-secondary);
  text-align: center;
  margin-bottom: 12px;
}

.time-row {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
  gap: 10px;
}

@media (max-width: 480px) {
  .time-row { grid-template-columns: 1fr; }
}

@media (max-width: 375px) {
  .type-row { gap: 8px; }
  .type-btn { padding: 10px 4px; }
  .type-icon { font-size: 18px; }
  .type-label { font-size: 11px; }
}
</style>

// src/components/forms/SleepForm.tsx
'use client'

import { useEffect, useState } from 'react'
import { useTranslation } from 'react-i18next'
import type { SleepType } from '@/types'
import { SLEEP_TYPE_LABELS } from '@/constants'
import { toDateTimeLocal, fromDateTimeLocal, formatDuration } from '@/utils/format'
import { db } from '@/db'
import { useBabies } from '@/stores/baby'
import { toast } from '@/stores/toast'
import { useActiveTimer } from '@/hooks/useActiveTimer'
import FormNotes from '@/components/common/FormNotes'
import FormActions from '@/components/common/FormActions'
import s from './SleepForm.module.css'

export interface SleepFormProps {
  editing?: { id: number; type: SleepType; startTime: number; endTime: number; notes?: string }
  onSaved?: () => void
  onCancelled?: () => void
  onStartRecord?: () => void
}

export default function SleepForm({ editing, onSaved, onCancelled, onStartRecord }: SleepFormProps) {
  const { t } = useTranslation()
  const { activeBabyId } = useBabies()
  const { getByKind, start: startTimer, reset: resetTimer } = useActiveTimer()

  const [type, setType] = useState<SleepType>(editing?.type ?? 'nap')
  const [notes, setNotes] = useState(editing?.notes ?? '')
  const [startTime, setStartTime] = useState(() => toDateTimeLocal(editing?.startTime ?? Date.now()))
  const [endTime, setEndTime] = useState(editing?.endTime ? toDateTimeLocal(editing.endTime) : '')

  const activeEntry = getByKind('sleep')
  const isRecording = !!activeEntry
  const isEditing = !!editing && !isRecording

  const durStart = fromDateTimeLocal(startTime)
  const durEnd = endTime ? fromDateTimeLocal(endTime) : undefined
  const durationText = durStart && durEnd && durEnd > durStart ? formatDuration(durEnd - durStart) : null

  const submitLabel = isEditing ? t('common.saveEdit') : isRecording ? t('sleep.endRecord') : t('sleep.startRecord')

  useEffect(() => {
    const entry = getByKind('sleep')
    if (!entry) return
    let stale = false
    void db.sleeps.get(entry.recordId).then((record) => {
      if (!record || stale) return
      setType(record.type)
      setNotes(record.notes ?? '')
      setStartTime(toDateTimeLocal(record.startTime))
      setEndTime('')
    })
    return () => {
      stale = true
    }
  }, [getByKind])

  async function submit() {
    try {
      const startTs = fromDateTimeLocal(startTime) ?? Date.now()
      const end = endTime ? fromDateTimeLocal(endTime) : undefined

      if (isRecording && activeEntry) {
        const endTs = end ?? Date.now()
        if (endTs <= startTs) {
          alert(t('sleep.invalidOrder'))
          return
        }
        await db.sleeps.update(activeEntry.recordId, {
          endTime: endTs,
          duration: endTs - startTs,
          updatedAt: Date.now(),
        })
        resetTimer(activeEntry.id)
        onSaved?.()
        return
      }

      if (isEditing && editing) {
        if (!end) {
          alert(t('sleep.invalidRange'))
          return
        }
        if (end <= startTs) {
          alert(t('sleep.invalidOrder'))
          return
        }
        await db.sleeps.update(editing.id, {
          type,
          startTime: startTs,
          endTime: end,
          notes: notes || undefined,
          updatedAt: Date.now(),
        })
        onSaved?.()
        return
      }

      if (activeBabyId == null) throw new Error(t('errors.noBaby'))
      const now = Date.now()
      const id = await db.sleeps.add({
        babyId: activeBabyId,
        type,
        startTime: startTs,
        endTime: undefined,
        duration: undefined,
        notes: notes || undefined,
        createdAt: now,
        updatedAt: now,
      })
      if (id == null) throw new Error(t('errors.addSleepFail'))
      startTimer('sleep', id, startTs)
      onStartRecord?.()
    } catch {
      toast(t('errors.generic'))
    }
  }

  const typeEntries = Object.entries(SLEEP_TYPE_LABELS) as [SleepType, string][]

  return (
    <div className="sleep-form">
      <p className="form-label">{t('sleep.typeLabel')}</p>
      <div className={s['type-row']}>
        {typeEntries.map(([key, label]) => (
          <button
            key={key}
            type="button"
            className={type === key ? `${s['type-btn']} ${s.selected}` : s['type-btn']}
            onClick={() => setType(key)}
          >
            <span className={s['type-icon']}>{key === 'night' ? '🌙' : '😴'}</span>
            <span className={s['type-label']}>{t(label)}</span>
          </button>
        ))}
      </div>

      <div className={s['time-row']}>
        <div className="form-field">
          <label className="form-label">{t('sleep.startLabel')}</label>
          <input
            value={startTime}
            type="datetime-local"
            placeholder={t('common.selectDateTime')}
            className="form-input"
            disabled={isRecording}
            onChange={(e) => setStartTime(e.target.value)}
          />
        </div>
        <div className="form-field">
          <label className="form-label">{t('sleep.endLabel')}</label>
          <input
            value={endTime}
            type="datetime-local"
            placeholder={t('common.selectDateTime')}
            className="form-input"
            onChange={(e) => setEndTime(e.target.value)}
          />
        </div>
      </div>

      {durationText && <p className={s['duration-hint']}>{durationText}</p>}

      <FormNotes value={notes} label={t('sleep.notesLabel')} placeholder={t('common.optional')} onChange={setNotes} />

      <FormActions editing={isEditing} submitLabel={submitLabel} onCancelled={onCancelled} onSave={submit} />
    </div>
  )
}
