// src/components/forms/TemperatureForm.vue
<script setup lang="ts">
import { ref } from 'vue'
import { useI18n } from 'vue-i18n'
import type { TemperatureMethod } from '@/types'
import { TEMP_METHOD_LIST } from '@/constants'
import { toDateTimeLocal, fromDateTimeLocal } from '@/utils/format'
import { useTemperatureStore } from '@/stores/temperature'
import FormNotes from '@/components/common/FormNotes.vue'
import FormActions from '@/components/common/FormActions.vue'

const { t } = useI18n()

const props = defineProps<{
  editing?: { id: number; time: number; value: number; method?: TemperatureMethod; notes?: string }
}>()
const emit = defineEmits<{ saved: []; cancelled: [] }>()

const temperatureStore = useTemperatureStore()

const value = ref<string>(props.editing?.value != null ? String(props.editing.value) : '')
const method = ref<TemperatureMethod | ''>(props.editing?.method ?? '')
const time = ref(toDateTimeLocal(props.editing?.time ?? Date.now()))
const notes = ref(props.editing?.notes ?? '')

async function submit() {
  const v = Number(value.value)
  if (value.value === '' || isNaN(v) || v < 35 || v > 43) {
    alert(t('temperature.invalidValue'))
    return
  }
  const ts = fromDateTimeLocal(time.value)
  if (ts == null || isNaN(ts)) {
    alert(t('temperature.invalidTime'))
    return
  }
  if (props.editing) {
    await temperatureStore.update(props.editing.id, {
      time: ts,
      value: v,
      method: method.value || undefined,
      notes: notes.value || undefined,
    })
  } else {
    await temperatureStore.add({
      time: ts,
      value: v,
      method: method.value || undefined,
      notes: notes.value || undefined,
    })
  }
  emit('saved')
}
</script>

<template>
  <div class="temperature-form">
    <div class="form-field">
      <label class="form-label">{{ t('temperature.valueLabel') }}</label>
      <div class="value-wrap">
        <input
          v-model="value"
          type="number"
          min="35"
          max="43"
          step="0.1"
          :placeholder="t('temperature.valuePlaceholder')"
          class="form-input"
          inputmode="decimal"
        />
        <span class="value-unit">℃</span>
      </div>
    </div>

    <p class="form-label">{{ t('temperature.methodLabel') }}</p>
    <div class="method-grid">
      <button
        v-for="opt in TEMP_METHOD_LIST"
        :key="opt.value"
        type="button"
        class="method-btn"
        :class="{ selected: method === opt.value }"
        @click="method = method === opt.value ? '' : opt.value"
      >
        <span class="method-icon">{{ opt.icon }}</span>
        <span class="method-label">{{ t(opt.label) }}</span>
      </button>
    </div>

    <div class="form-field">
      <label class="form-label">{{ t('temperature.timeLabel') }}</label>
      <input v-model="time" type="datetime-local" :placeholder="t('common.selectDateTime')" class="form-input" />
    </div>

    <FormNotes v-model="notes" :label="t('temperature.notesLabel')" :placeholder="t('common.optional')" />

    <FormActions :editing="props.editing != null" @cancelled="emit('cancelled')" @save="submit" />
  </div>
</template>

<style scoped>
.value-wrap {
  position: relative;
}

.value-wrap .form-input {
  padding-right: 34px;
}

.value-unit {
  position: absolute;
  right: 12px;
  top: 50%;
  transform: translateY(-50%);
  font-size: 14px;
  color: var(--text-muted);
  pointer-events: none;
}

.method-grid {
  display: grid;
  grid-template-columns: repeat(4, 1fr);
  gap: 8px;
  margin-bottom: 16px;
}

.method-btn {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 4px;
  padding: 10px 4px;
  border-radius: var(--radius-sm);
  border: 1.5px solid var(--border);
  background: var(--surface);
  transition: all 0.12s ease;
}

.method-btn.selected {
  border-color: var(--primary);
  background: var(--primary-soft);
}

.method-icon {
  font-size: 18px;
}

.method-label {
  font-size: 11px;
  font-weight: 600;
  color: var(--text-secondary);
  white-space: nowrap;
}
</style>

// src/components/forms/TemperatureForm.tsx
'use client'

import { useState } from 'react'
import { useTranslation } from 'react-i18next'
import type { TemperatureMethod } from '@/types'
import { TEMP_METHOD_LIST } from '@/constants'
import { toDateTimeLocal, fromDateTimeLocal } from '@/utils/format'
import { db } from '@/db'
import { useBabies } from '@/stores/baby'
import FormNotes from '@/components/common/FormNotes'
import FormActions from '@/components/common/FormActions'
import s from './TemperatureForm.module.css'

export interface TemperatureFormProps {
  editing?: { id: number; time: number; value: number; method?: TemperatureMethod; notes?: string }
  onSaved?: () => void
  onCancelled?: () => void
}

export default function TemperatureForm({ editing, onSaved, onCancelled }: TemperatureFormProps) {
  const { t } = useTranslation()
  const { activeBabyId } = useBabies()

  const [value, setValue] = useState(editing?.value != null ? String(editing.value) : '')
  const [method, setMethod] = useState<TemperatureMethod | ''>(editing?.method ?? '')
  const [time, setTime] = useState(() => toDateTimeLocal(editing?.time ?? Date.now()))
  const [notes, setNotes] = useState(editing?.notes ?? '')

  async function submit() {
    const v = Number(value)
    if (value === '' || isNaN(v) || v < 35 || v > 43) {
      alert(t('temperature.invalidValue'))
      return
    }
    const ts = fromDateTimeLocal(time)
    if (ts == null || isNaN(ts)) {
      alert(t('temperature.invalidTime'))
      return
    }
    if (editing) {
      await db.temperatures.update(editing.id, {
        time: ts,
        value: v,
        method: method || undefined,
        notes: notes || undefined,
        updatedAt: Date.now(),
      })
    } else {
      if (activeBabyId == null) throw new Error(t('errors.noBaby'))
      const now = Date.now()
      const id = await db.temperatures.add({
        babyId: activeBabyId,
        time: ts,
        value: v,
        method: method || undefined,
        notes: notes || undefined,
        createdAt: now,
        updatedAt: now,
      })
      if (id == null) throw new Error(t('errors.addRecordFail'))
    }
    onSaved?.()
  }

  return (
    <div className="temperature-form">
      <div className="form-field">
        <label className="form-label">{t('temperature.valueLabel')}</label>
        <div className={s['value-wrap']}>
          <input
            value={value}
            type="number"
            min={35}
            max={43}
            step={0.1}
            placeholder={t('temperature.valuePlaceholder')}
            className="form-input"
            inputMode="decimal"
            onChange={(e) => setValue(e.target.value)}
          />
          <span className={s['value-unit']}>℃</span>
        </div>
      </div>

      <p className="form-label">{t('temperature.methodLabel')}</p>
      <div className={s['method-grid']}>
        {TEMP_METHOD_LIST.map((opt) => (
          <button
            key={opt.value}
            type="button"
            className={method === opt.value ? `${s['method-btn']} ${s.selected}` : s['method-btn']}
            onClick={() => setMethod(method === opt.value ? '' : opt.value)}
          >
            <span className={s['method-icon']}>{opt.icon}</span>
            <span className={s['method-label']}>{t(opt.label)}</span>
          </button>
        ))}
      </div>

      <div className="form-field">
        <label className="form-label">{t('temperature.timeLabel')}</label>
        <input
          value={time}
          type="datetime-local"
          placeholder={t('common.selectDateTime')}
          className="form-input"
          onChange={(e) => setTime(e.target.value)}
        />
      </div>

      <FormNotes
        value={notes}
        label={t('temperature.notesLabel')}
        placeholder={t('common.optional')}
        onChange={setNotes}
      />

      <FormActions editing={editing != null} onCancelled={onCancelled} onSave={submit} />
    </div>
  )
}
